exports.devices = ['EL1', 'EL2', 'E1', 'E2', 'U1', 'U2']

exports.garages = ['E1', 'E2', 'U1', 'U2']

exports.modes = [
  'mode-no-func',
  'mode-data-edit',
  'mode-data-read',
  'mode-eme-1',
  'mode-eme-2',
  'mode-no-func',
  'mode-step',
  'mode-preset',
  'mode-auto'
]

exports.operations = [
  '---',
  'op-alarm-on',
  'op-alarm-off',
  'op-switch-mode',
  'op-change-pin',
  'op-stall-in',
  'op-stall-out',
  'op-shuffle-in',
  'op-shuffle-out',
  'op-stall-rsv',
  'op-req-exit',
  'op-req-entry',
  '---',
  '---',
  '---',
  '---'
]

exports.positions = [
  'Laser V1',
  'Laser V2',
  'Laser H1',
  'Laser H2',
  'Laser V1',
  'Laser V2',
  'Laser H1',
  'Laser H2',
  'Encoder R', // E1
  'Encoder R',
  'Encoder R', // U1
  'Encoder R'
]

exports.drives = [
  'IV1-EL1',
  'IV2-EL1',
  'IV1-E1',
  'IV1-U1',
  'IV1-EL2',
  'IV2-EL2',
  'IV1-E2',
  'IV1-U2'
]

exports.inputs1 = [
  { addr: 'E0.0', label: 'SA1' },
  { addr: 'E0.1', label: 'SA2' },
  { addr: 'E0.2', label: 'SA3' },
  { addr: 'E0.3', label: 'SA4' },
  { addr: 'E0.4', label: 'FE' },
  { addr: 'E0.5', label: 'RSI' },
  { addr: 'E0.6', label: '' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: '' },
  { addr: 'E1.1', label: '' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: '' },
  { addr: 'E1.5', label: '' },
  { addr: 'E1.6', label: '' },
  { addr: 'E1.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'S2' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: '' },
  { addr: 'E101.0', label: 'UC' },
  { addr: 'E101.1', label: 'RSI' },
  { addr: 'E101.2', label: 'FE1' },
  { addr: 'E101.3', label: 'APB' },
  { addr: 'E101.4', label: 'AP' },
  { addr: 'E101.5', label: 'RTD' },
  { addr: 'E101.6', label: 'ASR' },
  { addr: 'E101.7', label: 'AMC' },
  { addr: 'E102.0', label: 'IV2' },
  { addr: 'E102.1', label: 'IV3' },
  { addr: 'E102.2', label: 'SRL' },
  { addr: 'E102.3', label: '' },
  { addr: 'E102.4', label: '' },
  { addr: 'E102.5', label: '' },
  { addr: 'E102.6', label: '' },
  { addr: 'E102.7', label: '' },
  { addr: 'E103.0', label: 'ECA' },
  { addr: 'E103.1', label: 'ECB' },
  { addr: 'E103.2', label: 'EZE' },
  { addr: 'E103.3', label: 'EOE' },
  { addr: 'E103.4', label: 'EBZE' },
  { addr: 'E103.5', label: 'EBOE' },
  { addr: 'E103.6', label: 'FREL' },
  { addr: 'E103.7', label: 'FRER' },
  { addr: 'E104.0', label: 'FBE' },
  { addr: 'E104.1', label: 'FBBE' },
  { addr: 'E104.2', label: 'FPE' },
  { addr: 'E104.3', label: 'FDR1' },
  { addr: 'E104.4', label: 'FDL1' },
  { addr: 'E104.5', label: 'FDR2' },
  { addr: 'E104.6', label: 'FDL2' },
  { addr: 'E104.7', label: 'FTA1' },
  { addr: 'E105.0', label: 'FTA2' },
  { addr: 'E105.1', label: '' },
  { addr: 'E105.2', label: 'FLP' },
  { addr: 'E105.3', label: 'FLA' },
  { addr: 'E105.4', label: 'EXDE' },
  { addr: 'E105.5', label: 'EXHE' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: 'EZA' },
  { addr: 'E106.1', label: 'EOA' },
  { addr: 'E106.2', label: 'EBZA' },
  { addr: 'E106.3', label: 'EBOA' },
  { addr: 'E106.4', label: 'FBA' },
  { addr: 'E106.5', label: 'FBBA' },
  { addr: 'E106.6', label: 'FPA' },
  { addr: 'E106.7', label: '' },
  { addr: 'E107.0', label: 'EXDA' },
  { addr: 'E107.1', label: 'EXHA' },
  { addr: 'E107.2', label: 'DB32' },
  { addr: 'E107.3', label: 'DBHZ' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: '' },
  { addr: 'E107.6', label: '' },
  { addr: 'E107.7', label: '' }
]
exports.inputs3 = [
  { addr: 'E110.0', label: 'RSI' },
  { addr: 'E110.1', label: 'FE1' },
  { addr: 'E110.2', label: 'IV1' },
  { addr: 'E110.3', label: 'RTA' },
  { addr: 'E110.4', label: 'ASBK' },
  { addr: 'E110.5', label: 'FSBK' },
  { addr: 'E110.6', label: 'SA' },
  { addr: 'E110.7', label: 'UC' },
  { addr: 'E111.0', label: 'A' },
  { addr: 'E111.1', label: 'B' },
  { addr: 'E111.2', label: 'C' },
  { addr: 'E111.3', label: 'D' },
  { addr: 'E111.4', label: 'OK' },
  { addr: 'E111.5', label: 'S2' },
  { addr: 'E111.6', label: 'S2' },
  { addr: 'E111.7', label: 'S2' },
  { addr: 'E112.0', label: 'ASH' },
  { addr: 'E112.1', label: 'AMM' },
  { addr: 'E112.2', label: 'FE1' },
  { addr: 'E112.3', label: '' },
  { addr: 'E112.4', label: '' },
  { addr: 'E112.5', label: '' },
  { addr: 'E112.6', label: '' },
  { addr: 'E112.7', label: '' },
  { addr: 'E113.0', label: 'EOM' },
  { addr: 'E113.1', label: 'EZM' },
  { addr: 'E113.2', label: 'EMC' },
  { addr: 'E113.3', label: 'EXV' },
  { addr: 'E113.4', label: '' },
  { addr: 'E113.5', label: '' },
  { addr: 'E113.6', label: '' },
  { addr: 'E113.7', label: '' },
  { addr: 'E114.0', label: 'A' },
  { addr: 'E114.1', label: 'B' },
  { addr: 'E114.2', label: 'C' },
  { addr: 'E114.3', label: 'D' },
  { addr: 'E114.4', label: 'OK' },
  { addr: 'E114.5', label: 'S2' },
  { addr: 'E114.6', label: 'S2' },
  { addr: 'E114.7', label: 'S2' },
  { addr: 'E115.0', label: 'UC' },
  { addr: 'E115.1', label: 'FE2' },
  { addr: 'E115.2', label: 'IV2' },
  { addr: 'E115.3', label: 'RSI' },
  { addr: 'E115.4', label: 'AH' },
  { addr: 'E115.5', label: 'MTC' },
  { addr: 'E115.6', label: 'ATF' },
  { addr: 'E115.7', label: 'SRL' },
  { addr: 'E116.0', label: 'RMV' },
  { addr: 'E116.1', label: 'RMH' },
  { addr: 'E116.2', label: 'RES' },
  { addr: 'E116.3', label: 'REH' },
  { addr: 'E116.4', label: 'RCV' },
  { addr: 'E116.5', label: 'REAV' },
  { addr: 'E116.6', label: 'REAH' },
  { addr: 'E116.7', label: 'RCH' },
  { addr: 'E117.0', label: 'DB32' },
  { addr: 'E117.1', label: 'DBHZ' },
  { addr: 'E117.2', label: 'EM' },
  { addr: 'E117.3', label: 'FTXV' },
  { addr: 'E117.4', label: 'FTXH' },
  { addr: 'E117.5', label: 'FTAC' },
  { addr: 'E117.6', label: '' },
  { addr: 'E117.7', label: '' }
]
exports.inputs4 = [
  { addr: 'E200.0', label: 'A' },
  { addr: 'E200.1', label: 'B' },
  { addr: 'E200.2', label: 'C' },
  { addr: 'E200.3', label: 'D' },
  { addr: 'E200.4', label: 'S2' },
  { addr: 'E200.5', label: 'S2' },
  { addr: 'E200.6', label: 'S2' },
  { addr: 'E200.7', label: '' },
  { addr: 'E201.0', label: 'UC' },
  { addr: 'E201.1', label: 'RSI' },
  { addr: 'E201.2', label: 'FE1' },
  { addr: 'E201.3', label: 'APB' },
  { addr: 'E201.4', label: 'AP' },
  { addr: 'E201.5', label: 'RTD' },
  { addr: 'E201.6', label: 'ASR' },
  { addr: 'E201.7', label: 'AMC' },
  { addr: 'E202.0', label: 'IV2' },
  { addr: 'E202.1', label: 'IV3' },
  { addr: 'E202.2', label: 'SRL' },
  { addr: 'E202.3', label: '' },
  { addr: 'E202.4', label: '' },
  { addr: 'E202.5', label: '' },
  { addr: 'E202.6', label: '' },
  { addr: 'E202.7', label: '' },
  { addr: 'E203.0', label: 'ECA' },
  { addr: 'E203.1', label: 'ECB' },
  { addr: 'E203.2', label: 'EZE' },
  { addr: 'E203.3', label: 'EOE' },
  { addr: 'E203.4', label: 'EBZE' },
  { addr: 'E203.5', label: 'EBOE' },
  { addr: 'E203.6', label: 'FREL' },
  { addr: 'E203.7', label: 'FRER' },
  { addr: 'E204.0', label: 'FBE' },
  { addr: 'E204.1', label: 'FBBE' },
  { addr: 'E204.2', label: 'FPE' },
  { addr: 'E204.3', label: 'FDR1' },
  { addr: 'E204.4', label: 'FDL1' },
  { addr: 'E204.5', label: 'FDR2' },
  { addr: 'E204.6', label: 'FDL2' },
  { addr: 'E204.7', label: 'FTA1' },
  { addr: 'E205.0', label: 'FTA2' },
  { addr: 'E205.1', label: '' },
  { addr: 'E205.2', label: 'FLP' },
  { addr: 'E205.3', label: 'FLA' },
  { addr: 'E205.4', label: 'EXDE' },
  { addr: 'E205.5', label: 'EXHE' },
  { addr: 'E205.6', label: '' },
  { addr: 'E205.7', label: '' },
  { addr: 'E206.0', label: 'EZA' },
  { addr: 'E206.1', label: 'EOA' },
  { addr: 'E206.2', label: 'EBZA' },
  { addr: 'E206.3', label: 'EBOA' },
  { addr: 'E206.4', label: 'FBA' },
  { addr: 'E206.5', label: 'FBBA' },
  { addr: 'E206.6', label: 'FPA' },
  { addr: 'E206.7', label: '' },
  { addr: 'E207.0', label: 'EXDA' },
  { addr: 'E207.1', label: 'EXHA' },
  { addr: 'E207.2', label: 'DB32' },
  { addr: 'E207.3', label: 'DBHZ' },
  { addr: 'E207.4', label: '' },
  { addr: 'E207.5', label: '' },
  { addr: 'E207.6', label: '' },
  { addr: 'E207.7', label: '' }
]
exports.inputs5 = [
  { addr: 'E210.0', label: 'RSI' },
  { addr: 'E210.1', label: 'FE1' },
  { addr: 'E210.2', label: 'IV1' },
  { addr: 'E210.3', label: 'RTA' },
  { addr: 'E210.4', label: 'ASBK' },
  { addr: 'E210.5', label: 'FSBK' },
  { addr: 'E210.6', label: 'SA' },
  { addr: 'E210.7', label: 'UC' },
  { addr: 'E211.0', label: 'A' },
  { addr: 'E211.1', label: 'B' },
  { addr: 'E211.2', label: 'C' },
  { addr: 'E211.3', label: 'D' },
  { addr: 'E211.4', label: 'OK' },
  { addr: 'E211.5', label: 'S2' },
  { addr: 'E211.6', label: 'S2' },
  { addr: 'E211.7', label: 'S2' },
  { addr: 'E212.0', label: 'ASH' },
  { addr: 'E212.1', label: 'AMM' },
  { addr: 'E212.2', label: 'FE1' },
  { addr: 'E212.3', label: '' },
  { addr: 'E212.4', label: '' },
  { addr: 'E212.5', label: '' },
  { addr: 'E212.6', label: '' },
  { addr: 'E212.7', label: '' },
  { addr: 'E213.0', label: 'EOM' },
  { addr: 'E213.1', label: 'EZM' },
  { addr: 'E213.2', label: 'EMC' },
  { addr: 'E213.3', label: 'EXV' },
  { addr: 'E213.4', label: '' },
  { addr: 'E213.5', label: '' },
  { addr: 'E213.6', label: '' },
  { addr: 'E213.7', label: '' },
  { addr: 'E214.0', label: 'A' },
  { addr: 'E214.1', label: 'B' },
  { addr: 'E214.2', label: 'C' },
  { addr: 'E214.3', label: 'D' },
  { addr: 'E214.4', label: 'OK' },
  { addr: 'E214.5', label: 'S2' },
  { addr: 'E214.6', label: 'S2' },
  { addr: 'E214.7', label: 'S2' },
  { addr: 'E215.0', label: 'UC' },
  { addr: 'E215.1', label: 'FE2' },
  { addr: 'E215.2', label: 'IV2' },
  { addr: 'E215.3', label: 'RSI' },
  { addr: 'E215.4', label: 'AH' },
  { addr: 'E215.5', label: 'MTC' },
  { addr: 'E215.6', label: 'ATF' },
  { addr: 'E215.7', label: 'SRL' },
  { addr: 'E216.0', label: 'RMV' },
  { addr: 'E216.1', label: 'RMH' },
  { addr: 'E216.2', label: 'RES' },
  { addr: 'E216.3', label: 'REH' },
  { addr: 'E216.4', label: 'RCV' },
  { addr: 'E216.5', label: 'REAV' },
  { addr: 'E216.6', label: 'REAH' },
  { addr: 'E216.7', label: 'RCH' },
  { addr: 'E217.0', label: 'DB32' },
  { addr: 'E217.1', label: 'DBHZ' },
  { addr: 'E217.2', label: 'EM' },
  { addr: 'E217.3', label: 'FTXV' },
  { addr: 'E217.4', label: 'FTXH' },
  { addr: 'E217.5', label: 'FTAC' },
  { addr: 'E217.6', label: '' },
  { addr: 'E217.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'LS1' },
  { addr: 'A0.1', label: 'LS2' },
  { addr: 'A0.2', label: 'LS3' },
  { addr: 'A0.3', label: 'LS4' },
  { addr: 'A0.4', label: 'LA' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: '' },
  { addr: 'A0.7', label: '' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: '' },
  { addr: 'A1.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: 'DYA' },
  { addr: 'A100.1', label: 'DYB' },
  { addr: 'A100.2', label: 'DYC' },
  { addr: 'A100.3', label: 'DYD' },
  { addr: 'A100.4', label: 'AD1' },
  { addr: 'A100.5', label: 'AD2' },
  { addr: 'A100.6', label: 'AD3' },
  { addr: 'A100.7', label: 'STR' },
  { addr: 'A101.0', label: 'LC' },
  { addr: 'A101.1', label: 'LA' },
  { addr: 'A101.2', label: 'KBA2' },
  { addr: 'A101.3', label: 'KBA3' },
  { addr: 'A101.4', label: 'TRBE' },
  { addr: 'A101.5', label: 'TRBA' },
  { addr: 'A101.6', label: 'SCA' },
  { addr: 'A101.7', label: 'SCB' },
  { addr: 'A102.0', label: 'SPE' },
  { addr: 'A102.1', label: 'SPBE' },
  { addr: 'A102.2', label: 'SPA' },
  { addr: 'A102.3', label: 'SPBA' },
  { addr: 'A102.4', label: '' },
  { addr: 'A102.5', label: '' },
  { addr: 'A102.6', label: '' },
  { addr: 'A102.7', label: '' },
  { addr: 'A103.0', label: 'SOE' },
  { addr: 'A103.1', label: 'SZE' },
  { addr: 'A103.2', label: 'SOA' },
  { addr: 'A103.3', label: 'SZA' },
  { addr: 'A103.4', label: 'SBOE' },
  { addr: 'A103.5', label: 'SBZE' },
  { addr: 'A103.6', label: 'SBOA' },
  { addr: 'A103.7', label: 'SBZA' },
  { addr: 'A104.0', label: '' },
  { addr: 'A104.1', label: 'RFE' },
  { addr: 'A104.2', label: 'RFA' },
  { addr: 'A104.3', label: 'L1' },
  { addr: 'A104.4', label: 'L2' },
  { addr: 'A104.5', label: 'L3' },
  { addr: 'A104.6', label: 'L4' },
  { addr: 'A104.7', label: 'L5' },
  { addr: 'A105.0', label: '' },
  { addr: 'A105.1', label: '' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A110.0', label: 'LC' },
  { addr: 'A110.1', label: 'LA' },
  { addr: 'A110.2', label: 'KBA1' },
  { addr: 'A110.3', label: 'SBK1' },
  { addr: 'A110.4', label: 'SBK2' },
  { addr: 'A110.5', label: '' },
  { addr: 'A110.6', label: '' },
  { addr: 'A110.7', label: '' },
  { addr: 'A111.0', label: 'DYA' },
  { addr: 'A111.1', label: 'DYB' },
  { addr: 'A111.2', label: 'DYC' },
  { addr: 'A111.3', label: 'DYD' },
  { addr: 'A111.4', label: 'AD1' },
  { addr: 'A111.5', label: 'AD2' },
  { addr: 'A111.6', label: 'AD3' },
  { addr: 'A111.7', label: 'STR' },
  { addr: 'A112.0', label: 'SMA' },
  { addr: 'A112.1', label: 'SMB' },
  { addr: 'A112.2', label: 'LA' },
  { addr: 'A112.3', label: '' },
  { addr: 'A112.4', label: '' },
  { addr: 'A112.5', label: '' },
  { addr: 'A112.6', label: '' },
  { addr: 'A112.7', label: '' },
  { addr: 'A113.0', label: '' },
  { addr: 'A113.1', label: '' },
  { addr: 'A113.2', label: '' },
  { addr: 'A113.3', label: '' },
  { addr: 'A113.4', label: '' },
  { addr: 'A113.5', label: '' },
  { addr: 'A113.6', label: '' },
  { addr: 'A113.7', label: '' },
  { addr: 'A114.0', label: 'DYA' },
  { addr: 'A114.1', label: 'DYB' },
  { addr: 'A114.2', label: 'DYC' },
  { addr: 'A114.3', label: 'DYD' },
  { addr: 'A114.4', label: 'AD1' },
  { addr: 'A114.5', label: 'AD2' },
  { addr: 'A114.6', label: 'AD3' },
  { addr: 'A114.7', label: 'STR' },
  { addr: 'A115.0', label: 'LC' },
  { addr: 'A115.1', label: 'LA' },
  { addr: 'A115.2', label: 'KBA2' },
  { addr: 'A115.3', label: 'T101' },
  { addr: 'A115.4', label: 'T102' },
  { addr: 'A115.5', label: 'T2' },
  { addr: 'A115.6', label: 'TRA' },
  { addr: 'A115.7', label: 'TRB' },
  { addr: 'A116.0', label: 'T10F' },
  { addr: 'A116.1', label: 'KCS' },
  { addr: 'A116.2', label: 'KCV' },
  { addr: 'A116.3', label: 'KCH' },
  { addr: 'A116.4', label: '' },
  { addr: 'A116.5', label: '' },
  { addr: 'A116.6', label: '' },
  { addr: 'A116.7', label: '' },
  { addr: 'A117.0', label: '' },
  { addr: 'A117.1', label: '' },
  { addr: 'A117.2', label: '' },
  { addr: 'A117.3', label: '' },
  { addr: 'A117.4', label: '' },
  { addr: 'A117.5', label: '' },
  { addr: 'A117.6', label: '' },
  { addr: 'A117.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A200.0', label: 'DYA' },
  { addr: 'A200.1', label: 'DYB' },
  { addr: 'A200.2', label: 'DYC' },
  { addr: 'A200.3', label: 'DYD' },
  { addr: 'A200.4', label: 'AD1' },
  { addr: 'A200.5', label: 'AD2' },
  { addr: 'A200.6', label: 'AD3' },
  { addr: 'A200.7', label: 'STR' },
  { addr: 'A201.0', label: 'LC' },
  { addr: 'A201.1', label: 'LA' },
  { addr: 'A201.2', label: 'KBA2' },
  { addr: 'A201.3', label: 'KBA3' },
  { addr: 'A201.4', label: 'TRBE' },
  { addr: 'A201.5', label: 'TRBA' },
  { addr: 'A201.6', label: 'SCA' },
  { addr: 'A201.7', label: 'SCB' },
  { addr: 'A202.0', label: 'SPE' },
  { addr: 'A202.1', label: 'SPBE' },
  { addr: 'A202.2', label: 'SPA' },
  { addr: 'A202.3', label: 'SPBA' },
  { addr: 'A202.4', label: '' },
  { addr: 'A202.5', label: '' },
  { addr: 'A202.6', label: '' },
  { addr: 'A202.7', label: '' },
  { addr: 'A203.0', label: 'SOE' },
  { addr: 'A203.1', label: 'SZE' },
  { addr: 'A203.2', label: 'SOA' },
  { addr: 'A203.3', label: 'SZA' },
  { addr: 'A203.4', label: 'SBOE' },
  { addr: 'A203.5', label: 'SBZE' },
  { addr: 'A203.6', label: 'SBOA' },
  { addr: 'A203.7', label: 'SBZA' },
  { addr: 'A204.0', label: '' },
  { addr: 'A204.1', label: 'RFE' },
  { addr: 'A204.2', label: 'RFA' },
  { addr: 'A204.3', label: 'L1' },
  { addr: 'A204.4', label: 'L2' },
  { addr: 'A204.5', label: 'L3' },
  { addr: 'A204.6', label: 'L4' },
  { addr: 'A204.7', label: 'L5' },
  { addr: 'A205.0', label: '' },
  { addr: 'A205.1', label: '' },
  { addr: 'A205.2', label: '' },
  { addr: 'A205.3', label: '' },
  { addr: 'A205.4', label: '' },
  { addr: 'A205.5', label: '' },
  { addr: 'A205.6', label: '' },
  { addr: 'A205.7', label: '' }
]
exports.outputs5 = [
  { addr: 'A210.0', label: 'LC' },
  { addr: 'A210.1', label: 'LA' },
  { addr: 'A210.2', label: 'KBA1' },
  { addr: 'A210.3', label: 'SBK1' },
  { addr: 'A210.4', label: 'SBK2' },
  { addr: 'A210.5', label: '' },
  { addr: 'A210.6', label: '' },
  { addr: 'A210.7', label: '' },
  { addr: 'A211.0', label: 'DYA' },
  { addr: 'A211.1', label: 'DYB' },
  { addr: 'A211.2', label: 'DYC' },
  { addr: 'A211.3', label: 'DYD' },
  { addr: 'A211.4', label: 'AD1' },
  { addr: 'A211.5', label: 'AD2' },
  { addr: 'A211.6', label: 'AD3' },
  { addr: 'A211.7', label: 'STR' },
  { addr: 'A212.0', label: 'SMA' },
  { addr: 'A212.1', label: 'SMB' },
  { addr: 'A212.2', label: 'LA' },
  { addr: 'A212.3', label: '' },
  { addr: 'A212.4', label: '' },
  { addr: 'A212.5', label: '' },
  { addr: 'A212.6', label: '' },
  { addr: 'A212.7', label: '' },
  { addr: 'A213.0', label: '' },
  { addr: 'A213.1', label: '' },
  { addr: 'A213.2', label: '' },
  { addr: 'A213.3', label: '' },
  { addr: 'A213.4', label: '' },
  { addr: 'A213.5', label: '' },
  { addr: 'A213.6', label: '' },
  { addr: 'A213.7', label: '' },
  { addr: 'A214.0', label: 'DYA' },
  { addr: 'A214.1', label: 'DYB' },
  { addr: 'A214.2', label: 'DYC' },
  { addr: 'A214.3', label: 'DYD' },
  { addr: 'A214.4', label: 'AD1' },
  { addr: 'A214.5', label: 'AD2' },
  { addr: 'A214.6', label: 'AD3' },
  { addr: 'A214.7', label: 'STR' },
  { addr: 'A215.0', label: 'LC' },
  { addr: 'A215.1', label: 'LA' },
  { addr: 'A215.2', label: 'KBA2' },
  { addr: 'A215.3', label: 'T101' },
  { addr: 'A215.4', label: 'T102' },
  { addr: 'A215.5', label: 'T2' },
  { addr: 'A215.6', label: 'TRA' },
  { addr: 'A215.7', label: 'TRB' },
  { addr: 'A216.0', label: 'T10F' },
  { addr: 'A216.1', label: 'KCS' },
  { addr: 'A216.2', label: 'KCV' },
  { addr: 'A216.3', label: 'KCH' },
  { addr: 'A216.4', label: '' },
  { addr: 'A216.5', label: '' },
  { addr: 'A216.6', label: '' },
  { addr: 'A216.7', label: '' },
  { addr: 'A217.0', label: '' },
  { addr: 'A217.1', label: '' },
  { addr: 'A217.2', label: '' },
  { addr: 'A217.3', label: '' },
  { addr: 'A217.4', label: '' },
  { addr: 'A217.5', label: '' },
  { addr: 'A217.6', label: '' },
  { addr: 'A217.7', label: '' }
]
exports.merkers = [
  { addr: 'M0.0', label: '' },
  { addr: 'M0.1', label: '' },
  { addr: 'M0.2', label: '' },
  { addr: 'M0.3', label: '' },
  { addr: 'M0.4', label: '' },
  { addr: 'M0.5', label: '' },
  { addr: 'M0.6', label: '' },
  { addr: 'M0.7', label: '' },
  { addr: 'M1.0', label: '' },
  { addr: 'M1.1', label: '' },
  { addr: 'M1.2', label: '' },
  { addr: 'M1.3', label: '' },
  { addr: 'M1.4', label: '' },
  { addr: 'M1.5', label: '' },
  { addr: 'M1.6', label: '' },
  { addr: 'M1.7', label: '' },
  { addr: 'M2.0', label: '' },
  { addr: 'M2.1', label: '' },
  { addr: 'M2.2', label: '' },
  { addr: 'M2.3', label: '' },
  { addr: 'M2.4', label: '' },
  { addr: 'M2.5', label: '' },
  { addr: 'M2.6', label: '' },
  { addr: 'M2.7', label: '' },
  { addr: 'M3.0', label: '' },
  { addr: 'M3.1', label: '' },
  { addr: 'M3.2', label: '' },
  { addr: 'M3.3', label: '' },
  { addr: 'M3.4', label: '' },
  { addr: 'M3.5', label: '' },
  { addr: 'M3.6', label: '' },
  { addr: 'M3.7', label: '' },
  { addr: 'M4.0', label: '' },
  { addr: 'M4.1', label: '' },
  { addr: 'M4.2', label: '' },
  { addr: 'M4.3', label: '' },
  { addr: 'M4.4', label: '' },
  { addr: 'M4.5', label: '' },
  { addr: 'M4.6', label: '' },
  { addr: 'M4.7', label: '' },
  { addr: 'M5.0', label: '' },
  { addr: 'M5.1', label: '' },
  { addr: 'M5.2', label: '' },
  { addr: 'M5.3', label: '' },
  { addr: 'M5.4', label: '' },
  { addr: 'M5.5', label: '' },
  { addr: 'M5.6', label: '' },
  { addr: 'M5.7', label: '' },
  { addr: 'M6.0', label: '' },
  { addr: 'M6.1', label: '' },
  { addr: 'M6.2', label: '' },
  { addr: 'M6.3', label: '' },
  { addr: 'M6.4', label: '' },
  { addr: 'M6.5', label: '' },
  { addr: 'M6.6', label: '' },
  { addr: 'M6.7', label: '' },
  { addr: 'M7.0', label: '' },
  { addr: 'M7.1', label: '' },
  { addr: 'M7.2', label: '' },
  { addr: 'M7.3', label: '' },
  { addr: 'M7.4', label: '' },
  { addr: 'M7.5', label: '' },
  { addr: 'M7.6', label: '' },
  { addr: 'M7.7', label: '' }
]
exports.nodes = [
  { addr: 'PN0.0', label: '' },
  { addr: 'PN0.1', label: '' },
  { addr: 'PN0.2', label: '' },
  { addr: 'PN0.3', label: '' },
  { addr: 'PN0.4', label: '' },
  { addr: 'PN0.5', label: '' },
  { addr: 'PN0.6', label: '' },
  { addr: 'PN0.7', label: '' },
  { addr: 'PN1.0', label: '' },
  { addr: 'PN1.1', label: '' },
  { addr: 'PN1.2', label: '' },
  { addr: 'PN1.3', label: '' },
  { addr: 'PN1.4', label: '' },
  { addr: 'PN1.5', label: '' },
  { addr: 'PN1.6', label: '' },
  { addr: 'PN1.7', label: '' },
  { addr: 'PN2.0', label: '' },
  { addr: 'PN2.1', label: '' },
  { addr: 'PN2.2', label: '' },
  { addr: 'PN2.3', label: '' },
  { addr: 'PN2.4', label: '' },
  { addr: 'PN2.5', label: '' },
  { addr: 'PN2.6', label: '' },
  { addr: 'PN2.7', label: '' },
  { addr: 'PN3.0', label: '' },
  { addr: 'PN3.1', label: '' },
  { addr: 'PN3.2', label: '' },
  { addr: 'PN3.3', label: '' },
  { addr: 'PN3.4', label: '' },
  { addr: 'PN3.5', label: '' },
  { addr: 'PN3.6', label: '' },
  { addr: 'PN3.7', label: '' },
  { addr: 'PN4.0', label: '' },
  { addr: 'PN4.1', label: '' },
  { addr: 'PN4.2', label: '' },
  { addr: 'PN4.3', label: '' },
  { addr: 'PN4.4', label: '' },
  { addr: 'PN4.5', label: '' },
  { addr: 'PN4.6', label: '' },
  { addr: 'PN4.7', label: '' },
  { addr: 'PN5.0', label: '' },
  { addr: 'PN5.1', label: '' },
  { addr: 'PN5.2', label: '' },
  { addr: 'PN5.3', label: '' },
  { addr: 'PN5.4', label: '' },
  { addr: 'PN5.5', label: '' },
  { addr: 'PN5.6', label: '' },
  { addr: 'PN5.7', label: '' },
  { addr: 'PN6.0', label: '' },
  { addr: 'PN6.1', label: '' },
  { addr: 'PN6.2', label: '' },
  { addr: 'PN6.3', label: '' },
  { addr: 'PN6.4', label: '' },
  { addr: 'PN6.5', label: '' },
  { addr: 'PN6.6', label: '' },
  { addr: 'PN6.7', label: '' },
  { addr: 'PN7.0', label: '' },
  { addr: 'PN7.1', label: '' },
  { addr: 'PN7.2', label: '' },
  { addr: 'PN7.3', label: '' },
  { addr: 'PN7.4', label: '' },
  { addr: 'PN7.5', label: '' },
  { addr: 'PN7.6', label: '' },
  { addr: 'PN7.7', label: '' }
]
exports.motors = [
  { addr: 'MT0.0', label: '' },
  { addr: 'MT0.1', label: '' },
  { addr: 'MT0.2', label: '' },
  { addr: 'MT0.3', label: '' },
  { addr: 'MT0.4', label: '' },
  { addr: 'MT0.5', label: '' },
  { addr: 'MT0.6', label: '' },
  { addr: 'MT0.7', label: '' },
  { addr: 'MT1.0', label: '' },
  { addr: 'MT1.1', label: '' },
  { addr: 'MT1.2', label: '' },
  { addr: 'MT1.3', label: '' },
  { addr: 'MT1.4', label: '' },
  { addr: 'MT1.5', label: '' },
  { addr: 'MT1.6', label: '' },
  { addr: 'MT1.7', label: '' },
  { addr: 'MT2.0', label: '' },
  { addr: 'MT2.1', label: '' },
  { addr: 'MT2.2', label: '' },
  { addr: 'MT2.3', label: '' },
  { addr: 'MT2.4', label: '' },
  { addr: 'MT2.5', label: '' },
  { addr: 'MT2.6', label: '' },
  { addr: 'MT2.7', label: '' },
  { addr: 'MT3.0', label: '' },
  { addr: 'MT3.1', label: '' },
  { addr: 'MT3.2', label: '' },
  { addr: 'MT3.3', label: '' },
  { addr: 'MT3.4', label: '' },
  { addr: 'MT3.5', label: '' },
  { addr: 'MT3.6', label: '' },
  { addr: 'MT3.7', label: '' },
  { addr: 'MT4.0', label: '' },
  { addr: 'MT4.1', label: '' },
  { addr: 'MT4.2', label: '' },
  { addr: 'MT4.3', label: '' },
  { addr: 'MT4.4', label: '' },
  { addr: 'MT4.5', label: '' },
  { addr: 'MT4.6', label: '' },
  { addr: 'MT4.7', label: '' },
  { addr: 'MT5.0', label: '' },
  { addr: 'MT5.1', label: '' },
  { addr: 'MT5.2', label: '' },
  { addr: 'MT5.3', label: '' },
  { addr: 'MT5.4', label: '' },
  { addr: 'MT5.5', label: '' },
  { addr: 'MT5.6', label: '' },
  { addr: 'MT5.7', label: '' },
  { addr: 'MT6.0', label: '' },
  { addr: 'MT6.1', label: '' },
  { addr: 'MT6.2', label: '' },
  { addr: 'MT6.3', label: '' },
  { addr: 'MT6.4', label: '' },
  { addr: 'MT6.5', label: '' },
  { addr: 'MT6.6', label: '' },
  { addr: 'MT6.7', label: '' },
  { addr: 'MT7.0', label: '' },
  { addr: 'MT7.1', label: '' },
  { addr: 'MT7.2', label: '' },
  { addr: 'MT7.3', label: '' },
  { addr: 'MT7.4', label: '' },
  { addr: 'MT7.5', label: '' },
  { addr: 'MT7.6', label: '' },
  { addr: 'MT7.7', label: '' },
  { addr: 'MT8.0', label: '' },
  { addr: 'MT8.1', label: '' },
  { addr: 'MT8.2', label: '' },
  { addr: 'MT8.3', label: '' },
  { addr: 'MT8.4', label: '' },
  { addr: 'MT8.5', label: '' },
  { addr: 'MT8.6', label: '' },
  { addr: 'MT8.7', label: '' },
  { addr: 'MT9.0', label: '' },
  { addr: 'MT9.1', label: '' },
  { addr: 'MT9.2', label: '' },
  { addr: 'MT9.3', label: '' },
  { addr: 'MT9.4', label: '' },
  { addr: 'MT9.5', label: '' },
  { addr: 'MT9.6', label: '' },
  { addr: 'MT9.7', label: '' },
  { addr: 'MT10.0', label: '' },
  { addr: 'MT10.1', label: '' },
  { addr: 'MT10.2', label: '' },
  { addr: 'MT10.3', label: '' },
  { addr: 'MT10.4', label: '' },
  { addr: 'MT10.5', label: '' },
  { addr: 'MT10.6', label: '' },
  { addr: 'MT10.7', label: '' },
  { addr: 'MT11.0', label: '' },
  { addr: 'MT11.1', label: '' },
  { addr: 'MT11.2', label: '' },
  { addr: 'MT11.3', label: '' },
  { addr: 'MT11.4', label: '' },
  { addr: 'MT11.5', label: '' },
  { addr: 'MT11.6', label: '' },
  { addr: 'MT11.7', label: '' },
  { addr: 'MT12.0', label: '' },
  { addr: 'MT12.1', label: '' },
  { addr: 'MT12.2', label: '' },
  { addr: 'MT12.3', label: '' },
  { addr: 'MT12.4', label: '' },
  { addr: 'MT12.5', label: '' },
  { addr: 'MT12.6', label: '' },
  { addr: 'MT12.7', label: '' },
  { addr: 'MT13.0', label: '' },
  { addr: 'MT13.1', label: '' },
  { addr: 'MT13.2', label: '' },
  { addr: 'MT13.3', label: '' },
  { addr: 'MT13.4', label: '' },
  { addr: 'MT13.5', label: '' },
  { addr: 'MT13.6', label: '' },
  { addr: 'MT13.7', label: '' },
  { addr: 'MT14.0', label: '' },
  { addr: 'MT14.1', label: '' },
  { addr: 'MT14.2', label: '' },
  { addr: 'MT14.3', label: '' },
  { addr: 'MT14.4', label: '' },
  { addr: 'MT14.5', label: '' },
  { addr: 'MT14.6', label: '' },
  { addr: 'MT14.7', label: '' },
  { addr: 'MT15.0', label: '' },
  { addr: 'MT15.1', label: '' },
  { addr: 'MT15.2', label: '' },
  { addr: 'MT15.3', label: '' },
  { addr: 'MT15.4', label: '' },
  { addr: 'MT15.5', label: '' },
  { addr: 'MT15.6', label: '' },
  { addr: 'MT15.7', label: '' }
]
exports.alarms1 = [
  { class: 'EL1', label: 'AL1', info: 'al-sil-01' },
  { class: 'EL1', label: 'AL2', info: 'al-sil-02' },
  { class: 'EL1', label: 'AL3', info: 'al-sil-03' },
  { class: 'EL1', label: 'AL4', info: 'al-sil-04' },
  { class: 'EL1', label: 'AL5', info: 'al-sil-05' },
  { class: 'EL1', label: 'AL6', info: 'al-sil-06' },
  { class: 'EL1', label: 'AL7', info: 'al-sil-07' },
  { class: 'EL1', label: 'AL8', info: 'al-sil-08' },
  { class: 'EL1', label: 'AL9', info: 'al-sil-09' },
  { class: 'EL1', label: 'AL10', info: 'al-sil-10' },
  { class: 'EL1', label: 'AL11', info: 'al-sil-11' },
  { class: 'EL1', label: 'AL12', info: 'al-sil-12' },
  { class: 'EL1', label: 'AL13', info: 'al-sil-13' },
  { class: 'EL1', label: 'AL14', info: 'al-sil-14' },
  { class: 'EL1', label: 'AL15', info: 'al-sil-15' },
  { class: 'EL1', label: 'AL16', info: 'al-sil-16' },
  { class: 'EL1', label: 'AL17', info: 'al-v-to' },
  { class: 'EL1', label: 'AL18', info: 'al-v-fdbk' },
  { class: 'EL1', label: 'AL19', info: 'al-lv' },
  { class: 'EL1', label: 'AL20', info: 'al-lv-diff' },
  { class: 'EL1', label: 'AL21', info: 'al-v-lck-to' },
  { class: 'EL1', label: 'AL22', info: 'al-v-lck-fc' },
  { class: 'EL1', label: 'AL23', info: 'al-h-to' },
  { class: 'EL1', label: 'AL24', info: 'al-lh' },
  { class: 'EL1', label: 'AL25', info: 'al-lh-diff' },
  { class: 'EL1', label: 'AL26', info: '' },
  { class: 'EL1', label: 'AL27', info: '' },
  { class: 'EL1', label: 'AL28', info: '' },
  { class: 'EL1', label: 'AL29', info: '' },
  { class: 'EL1', label: 'AL30', info: '' },
  { class: 'EL1', label: 'AL31', info: '' },
  { class: 'EL1', label: 'AL32', info: '' },
  { class: 'EL1', label: 'AL33', info: '' },
  { class: 'EL1', label: 'AL34', info: '' },
  { class: 'EL1', label: 'AL35', info: '' },
  { class: 'EL1', label: 'AL36', info: '' },
  { class: 'EL1', label: 'AL37', info: '' },
  { class: 'EL1', label: 'AL38', info: '' },
  { class: 'EL1', label: 'AL39', info: '' },
  { class: 'EL1', label: 'AL40', info: '' },
  { class: 'EL1', label: 'AL41', info: '' },
  { class: 'EL1', label: 'AL42', info: '' },
  { class: 'EL1', label: 'AL43', info: '' },
  { class: 'EL1', label: 'AL44', info: '' },
  { class: 'EL1', label: 'AL45', info: '' },
  { class: 'EL1', label: 'AL46', info: '' },
  { class: 'EL1', label: 'AL47', info: '' },
  { class: 'EL1', label: 'AL48', info: '' },
  { class: 'EL1', label: 'AL49', info: '' },
  { class: 'EL1', label: 'AL50', info: '' },
  { class: 'EL1', label: 'AL51', info: '' },
  { class: 'EL1', label: 'AL52', info: '' },
  { class: 'EL1', label: 'AL53', info: '' },
  { class: 'EL1', label: 'AL54', info: '' },
  { class: 'EL1', label: 'AL55', info: '' },
  { class: 'EL1', label: 'AL56', info: '' },
  { class: 'EL1', label: 'AL57', info: '' },
  { class: 'EL1', label: 'AL58', info: '' },
  { class: 'EL1', label: 'AL59', info: '' },
  { class: 'EL1', label: 'AL60', info: '' },
  { class: 'EL1', label: 'AL61', info: '' },
  { class: 'EL1', label: 'AL62', info: '' },
  { class: 'EL1', label: 'AL63', info: '' },
  { class: 'EL1', label: 'AL64', info: '' }
]
exports.alarms2 = [
  { class: 'EL2', label: 'AL1', info: 'al-sil-01' },
  { class: 'EL2', label: 'AL2', info: 'al-sil-02' },
  { class: 'EL2', label: 'AL3', info: 'al-sil-03' },
  { class: 'EL2', label: 'AL4', info: 'al-sil-04' },
  { class: 'EL2', label: 'AL5', info: 'al-sil-05' },
  { class: 'EL2', label: 'AL6', info: 'al-sil-06' },
  { class: 'EL2', label: 'AL7', info: 'al-sil-07' },
  { class: 'EL2', label: 'AL8', info: 'al-sil-08' },
  { class: 'EL2', label: 'AL9', info: 'al-sil-09' },
  { class: 'EL2', label: 'AL10', info: 'al-sil-10' },
  { class: 'EL2', label: 'AL11', info: 'al-sil-11' },
  { class: 'EL2', label: 'AL12', info: 'al-sil-12' },
  { class: 'EL2', label: 'AL13', info: 'al-sil-13' },
  { class: 'EL2', label: 'AL14', info: 'al-sil-14' },
  { class: 'EL2', label: 'AL15', info: 'al-sil-15' },
  { class: 'EL2', label: 'AL16', info: 'al-sil-16' },
  { class: 'EL2', label: 'AL17', info: 'al-v-to' },
  { class: 'EL2', label: 'AL18', info: 'al-v-fdbk' },
  { class: 'EL2', label: 'AL19', info: 'al-lv' },
  { class: 'EL2', label: 'AL20', info: 'al-lv-diff' },
  { class: 'EL2', label: 'AL21', info: 'al-v-lck-to' },
  { class: 'EL2', label: 'AL22', info: 'al-v-lck-fc' },
  { class: 'EL2', label: 'AL23', info: 'al-h-to' },
  { class: 'EL2', label: 'AL24', info: 'al-lh' },
  { class: 'EL2', label: 'AL25', info: 'al-lh-diff' },
  { class: 'EL2', label: 'AL26', info: '' },
  { class: 'EL2', label: 'AL27', info: '' },
  { class: 'EL2', label: 'AL28', info: '' },
  { class: 'EL2', label: 'AL29', info: '' },
  { class: 'EL2', label: 'AL30', info: '' },
  { class: 'EL2', label: 'AL31', info: '' },
  { class: 'EL2', label: 'AL32', info: '' },
  { class: 'EL2', label: 'AL33', info: '' },
  { class: 'EL2', label: 'AL34', info: '' },
  { class: 'EL2', label: 'AL35', info: '' },
  { class: 'EL2', label: 'AL36', info: '' },
  { class: 'EL2', label: 'AL37', info: '' },
  { class: 'EL2', label: 'AL38', info: '' },
  { class: 'EL2', label: 'AL39', info: '' },
  { class: 'EL2', label: 'AL40', info: '' },
  { class: 'EL2', label: 'AL41', info: '' },
  { class: 'EL2', label: 'AL42', info: '' },
  { class: 'EL2', label: 'AL43', info: '' },
  { class: 'EL2', label: 'AL44', info: '' },
  { class: 'EL2', label: 'AL45', info: '' },
  { class: 'EL2', label: 'AL46', info: '' },
  { class: 'EL2', label: 'AL47', info: '' },
  { class: 'EL2', label: 'AL48', info: '' },
  { class: 'EL2', label: 'AL49', info: '' },
  { class: 'EL2', label: 'AL50', info: '' },
  { class: 'EL2', label: 'AL51', info: '' },
  { class: 'EL2', label: 'AL52', info: '' },
  { class: 'EL2', label: 'AL53', info: '' },
  { class: 'EL2', label: 'AL54', info: '' },
  { class: 'EL2', label: 'AL55', info: '' },
  { class: 'EL2', label: 'AL56', info: '' },
  { class: 'EL2', label: 'AL57', info: '' },
  { class: 'EL2', label: 'AL58', info: '' },
  { class: 'EL2', label: 'AL59', info: '' },
  { class: 'EL2', label: 'AL60', info: '' },
  { class: 'EL2', label: 'AL61', info: '' },
  { class: 'EL2', label: 'AL62', info: '' },
  { class: 'EL2', label: 'AL63', info: '' },
  { class: 'EL2', label: 'AL64', info: '' }
]
exports.alarms3 = [
  { class: 'E1', label: 'AL1', info: '' },
  { class: 'E1', label: 'AL2', info: '' },
  { class: 'E1', label: 'AL3', info: '' },
  { class: 'E1', label: 'AL4', info: '' },
  { class: 'E1', label: 'AL5', info: '' },
  { class: 'E1', label: 'AL6', info: '' },
  { class: 'E1', label: 'AL7', info: '' },
  { class: 'E1', label: 'AL8', info: '' },
  { class: 'E1', label: 'AL9', info: '' },
  { class: 'E1', label: 'AL10', info: '' },
  { class: 'E1', label: 'AL11', info: '' },
  { class: 'E1', label: 'AL12', info: '' },
  { class: 'E1', label: 'AL13', info: '' },
  { class: 'E1', label: 'AL14', info: '' },
  { class: 'E1', label: 'AL15', info: '' },
  { class: 'E1', label: 'AL16', info: '' },
  { class: 'E1', label: 'AL17', info: 'al-flap-to' },
  { class: 'E1', label: 'AL18', info: 'al-flap-fc' },
  { class: 'E1', label: 'AL19', info: 'al-spe-to' },
  { class: 'E1', label: 'AL20', info: 'al-spe-fc' },
  { class: 'E1', label: 'AL21', info: 'al-spbe-to' },
  { class: 'E1', label: 'AL22', info: 'al-spbe-fc' },
  { class: 'E1', label: 'AL23', info: 'al-r-to' },
  { class: 'E1', label: 'AL24', info: 'al-enr' },
  { class: 'E1', label: 'AL25', info: '' },
  { class: 'E1', label: 'AL26', info: '' },
  { class: 'E1', label: 'AL27', info: '' },
  { class: 'E1', label: 'AL28', info: '' },
  { class: 'E1', label: 'AL29', info: '' },
  { class: 'E1', label: 'AL30', info: '' },
  { class: 'E1', label: 'AL31', info: '' },
  { class: 'E1', label: 'AL32', info: '' },
  { class: 'E1', label: 'AL33', info: '' },
  { class: 'E1', label: 'AL34', info: '' },
  { class: 'E1', label: 'AL35', info: '' },
  { class: 'E1', label: 'AL36', info: '' },
  { class: 'E1', label: 'AL37', info: '' },
  { class: 'E1', label: 'AL38', info: '' },
  { class: 'E1', label: 'AL39', info: '' },
  { class: 'E1', label: 'AL40', info: '' },
  { class: 'E1', label: 'AL41', info: '' },
  { class: 'E1', label: 'AL42', info: '' },
  { class: 'E1', label: 'AL43', info: '' },
  { class: 'E1', label: 'AL44', info: '' },
  { class: 'E1', label: 'AL45', info: '' },
  { class: 'E1', label: 'AL46', info: '' },
  { class: 'E1', label: 'AL47', info: '' },
  { class: 'E1', label: 'AL48', info: '' },
  { class: 'E1', label: 'AL49', info: '' },
  { class: 'E1', label: 'AL50', info: '' },
  { class: 'E1', label: 'AL51', info: '' },
  { class: 'E1', label: 'AL52', info: '' },
  { class: 'E1', label: 'AL53', info: '' },
  { class: 'E1', label: 'AL54', info: '' },
  { class: 'E1', label: 'AL55', info: '' },
  { class: 'E1', label: 'AL56', info: '' },
  { class: 'E1', label: 'AL57', info: '' },
  { class: 'E1', label: 'AL58', info: '' },
  { class: 'E1', label: 'AL59', info: '' },
  { class: 'E1', label: 'AL60', info: '' },
  { class: 'E1', label: 'AL61', info: '' },
  { class: 'E1', label: 'AL62', info: '' },
  { class: 'E1', label: 'AL63', info: '' },
  { class: 'E1', label: 'AL64', info: '' }
]
exports.alarms4 = [
  { class: 'E2', label: 'AL1', info: '' },
  { class: 'E2', label: 'AL2', info: '' },
  { class: 'E2', label: 'AL3', info: '' },
  { class: 'E2', label: 'AL4', info: '' },
  { class: 'E2', label: 'AL5', info: '' },
  { class: 'E2', label: 'AL6', info: '' },
  { class: 'E2', label: 'AL7', info: '' },
  { class: 'E2', label: 'AL8', info: '' },
  { class: 'E2', label: 'AL9', info: '' },
  { class: 'E2', label: 'AL10', info: '' },
  { class: 'E2', label: 'AL11', info: '' },
  { class: 'E2', label: 'AL12', info: '' },
  { class: 'E2', label: 'AL13', info: '' },
  { class: 'E2', label: 'AL14', info: '' },
  { class: 'E2', label: 'AL15', info: '' },
  { class: 'E2', label: 'AL16', info: '' },
  { class: 'E2', label: 'AL17', info: 'al-flap-to' },
  { class: 'E2', label: 'AL18', info: 'al-flap-fc' },
  { class: 'E2', label: 'AL19', info: 'al-spe-to' },
  { class: 'E2', label: 'AL20', info: 'al-spe-fc' },
  { class: 'E2', label: 'AL21', info: 'al-spbe-to' },
  { class: 'E2', label: 'AL22', info: 'al-spbe-fc' },
  { class: 'E2', label: 'AL23', info: 'al-r-to' },
  { class: 'E2', label: 'AL24', info: 'al-enr' },
  { class: 'E2', label: 'AL25', info: '' },
  { class: 'E2', label: 'AL26', info: '' },
  { class: 'E2', label: 'AL27', info: '' },
  { class: 'E2', label: 'AL28', info: '' },
  { class: 'E2', label: 'AL29', info: '' },
  { class: 'E2', label: 'AL30', info: '' },
  { class: 'E2', label: 'AL31', info: '' },
  { class: 'E2', label: 'AL32', info: '' },
  { class: 'E2', label: 'AL33', info: '' },
  { class: 'E2', label: 'AL34', info: '' },
  { class: 'E2', label: 'AL35', info: '' },
  { class: 'E2', label: 'AL36', info: '' },
  { class: 'E2', label: 'AL37', info: '' },
  { class: 'E2', label: 'AL38', info: '' },
  { class: 'E2', label: 'AL39', info: '' },
  { class: 'E2', label: 'AL40', info: '' },
  { class: 'E2', label: 'AL41', info: '' },
  { class: 'E2', label: 'AL42', info: '' },
  { class: 'E2', label: 'AL43', info: '' },
  { class: 'E2', label: 'AL44', info: '' },
  { class: 'E2', label: 'AL45', info: '' },
  { class: 'E2', label: 'AL46', info: '' },
  { class: 'E2', label: 'AL47', info: '' },
  { class: 'E2', label: 'AL48', info: '' },
  { class: 'E2', label: 'AL49', info: '' },
  { class: 'E2', label: 'AL50', info: '' },
  { class: 'E2', label: 'AL51', info: '' },
  { class: 'E2', label: 'AL52', info: '' },
  { class: 'E2', label: 'AL53', info: '' },
  { class: 'E2', label: 'AL54', info: '' },
  { class: 'E2', label: 'AL55', info: '' },
  { class: 'E2', label: 'AL56', info: '' },
  { class: 'E2', label: 'AL57', info: '' },
  { class: 'E2', label: 'AL58', info: '' },
  { class: 'E2', label: 'AL59', info: '' },
  { class: 'E2', label: 'AL60', info: '' },
  { class: 'E2', label: 'AL61', info: '' },
  { class: 'E2', label: 'AL62', info: '' },
  { class: 'E2', label: 'AL63', info: '' },
  { class: 'E2', label: 'AL64', info: '' }
]
exports.alarms5 = [
  { class: 'U1', label: 'AL1', info: '' },
  { class: 'U1', label: 'AL2', info: '' },
  { class: 'U1', label: 'AL3', info: '' },
  { class: 'U1', label: 'AL4', info: '' },
  { class: 'U1', label: 'AL5', info: '' },
  { class: 'U1', label: 'AL6', info: '' },
  { class: 'U1', label: 'AL7', info: '' },
  { class: 'U1', label: 'AL8', info: '' },
  { class: 'U1', label: 'AL9', info: '' },
  { class: 'U1', label: 'AL10', info: '' },
  { class: 'U1', label: 'AL11', info: '' },
  { class: 'U1', label: 'AL12', info: '' },
  { class: 'U1', label: 'AL13', info: '' },
  { class: 'U1', label: 'AL14', info: '' },
  { class: 'U1', label: 'AL15', info: '' },
  { class: 'U1', label: 'AL16', info: '' },
  { class: 'U1', label: 'AL17', info: '' },
  { class: 'U1', label: 'AL18', info: '' },
  { class: 'U1', label: 'AL19', info: 'al-spa-to' },
  { class: 'U1', label: 'AL20', info: 'al-spa-fc' },
  { class: 'U1', label: 'AL21', info: 'al-spba-to' },
  { class: 'U1', label: 'AL22', info: 'al-spba-fc' },
  { class: 'U1', label: 'AL23', info: 'al-r-to' },
  { class: 'U1', label: 'AL24', info: 'al-enr' },
  { class: 'U1', label: 'AL25', info: '' },
  { class: 'U1', label: 'AL26', info: '' },
  { class: 'U1', label: 'AL27', info: '' },
  { class: 'U1', label: 'AL28', info: '' },
  { class: 'U1', label: 'AL29', info: '' },
  { class: 'U1', label: 'AL30', info: '' },
  { class: 'U1', label: 'AL31', info: '' },
  { class: 'U1', label: 'AL32', info: '' },
  { class: 'U1', label: 'AL33', info: '' },
  { class: 'U1', label: 'AL34', info: '' },
  { class: 'U1', label: 'AL35', info: '' },
  { class: 'U1', label: 'AL36', info: '' },
  { class: 'U1', label: 'AL37', info: '' },
  { class: 'U1', label: 'AL38', info: '' },
  { class: 'U1', label: 'AL39', info: '' },
  { class: 'U1', label: 'AL40', info: '' },
  { class: 'U1', label: 'AL41', info: '' },
  { class: 'U1', label: 'AL42', info: '' },
  { class: 'U1', label: 'AL43', info: '' },
  { class: 'U1', label: 'AL44', info: '' },
  { class: 'U1', label: 'AL45', info: '' },
  { class: 'U1', label: 'AL46', info: '' },
  { class: 'U1', label: 'AL47', info: '' },
  { class: 'U1', label: 'AL48', info: '' },
  { class: 'U1', label: 'AL49', info: '' },
  { class: 'U1', label: 'AL50', info: '' },
  { class: 'U1', label: 'AL51', info: '' },
  { class: 'U1', label: 'AL52', info: '' },
  { class: 'U1', label: 'AL53', info: '' },
  { class: 'U1', label: 'AL54', info: '' },
  { class: 'U1', label: 'AL55', info: '' },
  { class: 'U1', label: 'AL56', info: '' },
  { class: 'U1', label: 'AL57', info: '' },
  { class: 'U1', label: 'AL58', info: '' },
  { class: 'U1', label: 'AL59', info: '' },
  { class: 'U1', label: 'AL60', info: '' },
  { class: 'U1', label: 'AL61', info: '' },
  { class: 'U1', label: 'AL62', info: '' },
  { class: 'U1', label: 'AL63', info: '' },
  { class: 'U1', label: 'AL64', info: '' }
]
exports.alarms6 = [
  { class: 'U2', label: 'AL1', info: '' },
  { class: 'U2', label: 'AL2', info: '' },
  { class: 'U2', label: 'AL3', info: '' },
  { class: 'U2', label: 'AL4', info: '' },
  { class: 'U2', label: 'AL5', info: '' },
  { class: 'U2', label: 'AL6', info: '' },
  { class: 'U2', label: 'AL7', info: '' },
  { class: 'U2', label: 'AL8', info: '' },
  { class: 'U2', label: 'AL9', info: '' },
  { class: 'U2', label: 'AL10', info: '' },
  { class: 'U2', label: 'AL11', info: '' },
  { class: 'U2', label: 'AL12', info: '' },
  { class: 'U2', label: 'AL13', info: '' },
  { class: 'U2', label: 'AL14', info: '' },
  { class: 'U2', label: 'AL15', info: '' },
  { class: 'U2', label: 'AL16', info: '' },
  { class: 'U2', label: 'AL17', info: '' },
  { class: 'U2', label: 'AL18', info: '' },
  { class: 'U2', label: 'AL19', info: 'al-spa-to' },
  { class: 'U2', label: 'AL20', info: 'al-spa-fc' },
  { class: 'U2', label: 'AL21', info: 'al-spba-to' },
  { class: 'U2', label: 'AL22', info: 'al-spba-fc' },
  { class: 'U2', label: 'AL23', info: 'al-r-to' },
  { class: 'U2', label: 'AL24', info: 'al-enr' },
  { class: 'U2', label: 'AL25', info: '' },
  { class: 'U2', label: 'AL26', info: '' },
  { class: 'U2', label: 'AL27', info: '' },
  { class: 'U2', label: 'AL28', info: '' },
  { class: 'U2', label: 'AL29', info: '' },
  { class: 'U2', label: 'AL30', info: '' },
  { class: 'U2', label: 'AL31', info: '' },
  { class: 'U2', label: 'AL32', info: '' },
  { class: 'U2', label: 'AL33', info: '' },
  { class: 'U2', label: 'AL34', info: '' },
  { class: 'U2', label: 'AL35', info: '' },
  { class: 'U2', label: 'AL36', info: '' },
  { class: 'U2', label: 'AL37', info: '' },
  { class: 'U2', label: 'AL38', info: '' },
  { class: 'U2', label: 'AL39', info: '' },
  { class: 'U2', label: 'AL40', info: '' },
  { class: 'U2', label: 'AL41', info: '' },
  { class: 'U2', label: 'AL42', info: '' },
  { class: 'U2', label: 'AL43', info: '' },
  { class: 'U2', label: 'AL44', info: '' },
  { class: 'U2', label: 'AL45', info: '' },
  { class: 'U2', label: 'AL46', info: '' },
  { class: 'U2', label: 'AL47', info: '' },
  { class: 'U2', label: 'AL48', info: '' },
  { class: 'U2', label: 'AL49', info: '' },
  { class: 'U2', label: 'AL50', info: '' },
  { class: 'U2', label: 'AL51', info: '' },
  { class: 'U2', label: 'AL52', info: '' },
  { class: 'U2', label: 'AL53', info: '' },
  { class: 'U2', label: 'AL54', info: '' },
  { class: 'U2', label: 'AL55', info: '' },
  { class: 'U2', label: 'AL56', info: '' },
  { class: 'U2', label: 'AL57', info: '' },
  { class: 'U2', label: 'AL58', info: '' },
  { class: 'U2', label: 'AL59', info: '' },
  { class: 'U2', label: 'AL60', info: '' },
  { class: 'U2', label: 'AL61', info: '' },
  { class: 'U2', label: 'AL62', info: '' },
  { class: 'U2', label: 'AL63', info: '' },
  { class: 'U2', label: 'AL64', info: '' }
]
