exports.devices = ['SH1', 'SH2', 'EL1', 'EL2']

exports.modes = [
  'mode-no-func',
  'mode-data-edit',
  'mode-data-read',
  'mode-eme-1',
  'mode-eme-2',
  'mode-no-func',
  'mode-step',
  'mode-preset',
  'mode-auto'
]

exports.operations = [
  '---',
  'op-alarm-on',
  'op-alarm-off',
  'op-switch-mode',
  'op-change-pin',
  'op-stall-in',
  'op-stall-out',
  'op-shuffle-in',
  'op-shuffle-out',
  'op-stall-rsv',
  'op-req-exit',
  'op-req-entry',
  '---',
  '---',
  '---',
  '---'
]

exports.positions = [
  'Laser H1',
  'Laser H2',
  'Encoder R',
  'Laser H1',
  'Laser H2',
  'Encoder R',
  'Laser V1',
  'Laser V2'
]

exports.inputs1 = [
  { addr: 'E0.0', label: 'A' },
  { addr: 'E0.1', label: 'B' },
  { addr: 'E0.2', label: 'C' },
  { addr: 'E0.3', label: 'D' },
  { addr: 'E0.4', label: 'STR' },
  { addr: 'E0.5', label: 'OK' },
  { addr: 'E0.6', label: 'DAT' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: 'SFA' },
  { addr: 'E1.1', label: 'SFB' },
  { addr: 'E1.2', label: '' },
  { addr: 'E1.3', label: '' },
  { addr: 'E1.4', label: 'FAL' },
  { addr: 'E1.5', label: 'TLC' },
  { addr: 'E1.6', label: 'FE3' },
  { addr: 'E1.7', label: 'RS1' },
  { addr: 'E2.0', label: '' },
  { addr: 'E2.1', label: '' },
  { addr: 'E2.2', label: '' },
  { addr: 'E2.3', label: '' },
  { addr: 'E2.4', label: '' },
  { addr: 'E2.5', label: '' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: '' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: '' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'A' },
  { addr: 'E101.1', label: 'B' },
  { addr: 'E101.2', label: 'C' },
  { addr: 'E101.3', label: 'D' },
  { addr: 'E101.4', label: 'STR' },
  { addr: 'E101.5', label: 'OK' },
  { addr: 'E101.6', label: 'DAT' },
  { addr: 'E101.7', label: 'UC' },
  { addr: 'E102.0', label: 'KEXPV' },
  { addr: 'E102.1', label: 'FTC' },
  { addr: 'E102.2', label: 'EXPV' },
  { addr: 'E102.3', label: 'EFB' },
  { addr: 'E102.4', label: 'ECA' },
  { addr: 'E102.5', label: 'ECB' },
  { addr: 'E102.6', label: 'AMC' },
  { addr: 'E102.7', label: 'APE' },
  { addr: 'E103.0', label: 'FTXV' },
  { addr: 'E103.1', label: 'FTXH' },
  { addr: 'E103.2', label: 'RS3' },
  { addr: 'E103.3', label: '' },
  { addr: 'E103.4', label: 'DB32' },
  { addr: 'E103.5', label: 'DBHZ' },
  { addr: 'E103.6', label: 'KXPE' },
  { addr: 'E103.7', label: '' },
  { addr: 'E104.0', label: 'KBA' },
  { addr: 'E104.1', label: 'IV2' },
  { addr: 'E104.2', label: 'SA' },
  { addr: 'E104.3', label: 'IV1' },
  { addr: 'E104.4', label: 'FDBK' },
  { addr: 'E104.5', label: 'ASBK' },
  { addr: 'E104.6', label: 'RT12' },
  { addr: 'E104.7', label: '' },
  { addr: 'E105.0', label: 'FE1' },
  { addr: 'E105.1', label: 'POD' },
  { addr: 'E105.2', label: 'AF8' },
  { addr: 'E105.3', label: 'ASH' },
  { addr: 'E105.4', label: 'AHIV' },
  { addr: 'E105.5', label: 'FLA2' },
  { addr: 'E105.6', label: 'EOE2' },
  { addr: 'E105.7', label: 'EZE2' },
  { addr: 'E106.0', label: 'EZE' },
  { addr: 'E106.1', label: 'EOE' },
  { addr: 'E106.2', label: 'FBE' },
  { addr: 'E106.3', label: 'FPE' },
  { addr: 'E106.4', label: 'FDR1' },
  { addr: 'E106.5', label: 'FDL1' },
  { addr: 'E106.6', label: 'FTA1' },
  { addr: 'E106.7', label: 'FTA2' },
  { addr: 'E107.0', label: 'FLP1' },
  { addr: 'E107.1', label: 'FLP2' },
  { addr: 'E107.2', label: 'FLA1' },
  { addr: 'E107.3', label: 'FDR2' },
  { addr: 'E107.4', label: 'FDL2' },
  { addr: 'E107.5', label: 'FRE' },
  { addr: 'E107.6', label: 'RX1' },
  { addr: 'E107.7', label: 'RX2' },
  { addr: 'E108.0', label: '' },
  { addr: 'E108.1', label: '' },
  { addr: 'E108.2', label: '' },
  { addr: 'E108.3', label: '' },
  { addr: 'E108.4', label: '' },
  { addr: 'E108.5', label: '' },
  { addr: 'E108.6', label: '' },
  { addr: 'E108.7', label: '' },
  { addr: 'E109.0', label: 'EOM1' },
  { addr: 'E109.1', label: 'EZM1' },
  { addr: 'E109.2', label: 'AMM1' },
  { addr: 'E109.3', label: 'EOM2' },
  { addr: 'E109.4', label: 'EZM2' },
  { addr: 'E109.5', label: 'AMM2' },
  { addr: 'E109.6', label: '' },
  { addr: 'E109.7', label: '' }
]
exports.inputs3 = [
  { addr: 'E110.0', label: 'RMV' },
  { addr: 'E110.1', label: 'RMH' },
  { addr: 'E110.2', label: 'RES' },
  { addr: 'E110.3', label: 'REH' },
  { addr: 'E110.4', label: 'RCV' },
  { addr: 'E110.5', label: 'REAV' },
  { addr: 'E110.6', label: 'REAH' },
  { addr: 'E110.7', label: 'RCH' },
  { addr: 'E111.0', label: 'FTXV' },
  { addr: 'E111.1', label: 'FTXH' },
  { addr: 'E111.2', label: '' },
  { addr: 'E111.3', label: 'EM' },
  { addr: 'E111.4', label: 'EHP1' },
  { addr: 'E111.5', label: 'EHP2' },
  { addr: 'E111.6', label: 'FTAC' },
  { addr: 'E111.7', label: 'EXD' },
  { addr: 'E112.0', label: 'AD' },
  { addr: 'E112.1', label: 'MTC' },
  { addr: 'E112.2', label: 'TCR' },
  { addr: 'E112.3', label: '' },
  { addr: 'E112.4', label: '' },
  { addr: 'E112.5', label: '' },
  { addr: 'E112.6', label: '' },
  { addr: 'E112.7', label: '' }
]
exports.inputs4 = [
  { addr: 'E200.0', label: 'A' },
  { addr: 'E200.1', label: 'B' },
  { addr: 'E200.2', label: 'C' },
  { addr: 'E200.3', label: 'D' },
  { addr: 'E200.4', label: 'OK' },
  { addr: 'E200.5', label: 'S2' },
  { addr: 'E200.6', label: 'S2' },
  { addr: 'E200.7', label: 'S2' },
  { addr: 'E201.0', label: 'A' },
  { addr: 'E201.1', label: 'B' },
  { addr: 'E201.2', label: 'C' },
  { addr: 'E201.3', label: 'D' },
  { addr: 'E201.4', label: 'STR' },
  { addr: 'E201.5', label: 'OK' },
  { addr: 'E201.6', label: 'DAT' },
  { addr: 'E201.7', label: 'UC' },
  { addr: 'E202.0', label: 'KEXPV' },
  { addr: 'E202.1', label: 'FTC' },
  { addr: 'E202.2', label: 'EXPV' },
  { addr: 'E202.3', label: 'EFB' },
  { addr: 'E202.4', label: 'ECA' },
  { addr: 'E202.5', label: 'ECB' },
  { addr: 'E202.6', label: 'AMC' },
  { addr: 'E202.7', label: 'APE' },
  { addr: 'E203.0', label: 'FTXV' },
  { addr: 'E203.1', label: 'FTXH' },
  { addr: 'E203.2', label: 'RS3' },
  { addr: 'E203.3', label: '' },
  { addr: 'E203.4', label: 'DB32' },
  { addr: 'E203.5', label: 'DBHZ' },
  { addr: 'E203.6', label: 'KXPE' },
  { addr: 'E203.7', label: '' },
  { addr: 'E204.0', label: 'KBA' },
  { addr: 'E204.1', label: 'IV2' },
  { addr: 'E204.2', label: 'SA' },
  { addr: 'E204.3', label: 'IV1' },
  { addr: 'E204.4', label: 'FDBK' },
  { addr: 'E204.5', label: 'ASBK' },
  { addr: 'E204.6', label: 'RT12' },
  { addr: 'E204.7', label: '' },
  { addr: 'E205.0', label: 'FE1' },
  { addr: 'E205.1', label: 'POD' },
  { addr: 'E205.2', label: 'AF8' },
  { addr: 'E205.3', label: 'ASH' },
  { addr: 'E205.4', label: 'AHIV' },
  { addr: 'E205.5', label: 'FLA2' },
  { addr: 'E205.6', label: 'EOE2' },
  { addr: 'E205.7', label: 'EZE2' },
  { addr: 'E206.0', label: 'EZE' },
  { addr: 'E206.1', label: 'EOE' },
  { addr: 'E206.2', label: 'FBE' },
  { addr: 'E206.3', label: 'FPE' },
  { addr: 'E206.4', label: 'FDR1' },
  { addr: 'E206.5', label: 'FDL1' },
  { addr: 'E206.6', label: 'FTA1' },
  { addr: 'E206.7', label: 'FTA2' },
  { addr: 'E207.0', label: 'FLP1' },
  { addr: 'E207.1', label: 'FLP2' },
  { addr: 'E207.2', label: 'FLA1' },
  { addr: 'E207.3', label: 'FDR2' },
  { addr: 'E207.4', label: 'FDL2' },
  { addr: 'E207.5', label: 'FRE' },
  { addr: 'E207.6', label: 'RX1' },
  { addr: 'E207.7', label: 'RX2' },
  { addr: 'E208.0', label: '' },
  { addr: 'E208.1', label: '' },
  { addr: 'E208.2', label: '' },
  { addr: 'E208.3', label: '' },
  { addr: 'E208.4', label: '' },
  { addr: 'E208.5', label: '' },
  { addr: 'E208.6', label: '' },
  { addr: 'E208.7', label: '' },
  { addr: 'E209.0', label: 'EOM1' },
  { addr: 'E209.1', label: 'EZM1' },
  { addr: 'E209.2', label: 'AMM1' },
  { addr: 'E209.3', label: 'EOM2' },
  { addr: 'E209.4', label: 'EZM2' },
  { addr: 'E209.5', label: 'AMM2' },
  { addr: 'E209.6', label: '' },
  { addr: 'E209.7', label: '' }
]
exports.inputs5 = [
  { addr: 'E210.0', label: 'RMV' },
  { addr: 'E210.1', label: 'RMH' },
  { addr: 'E210.2', label: 'RES' },
  { addr: 'E210.3', label: 'REH' },
  { addr: 'E210.4', label: 'RCV' },
  { addr: 'E210.5', label: 'REAV' },
  { addr: 'E210.6', label: 'REAH' },
  { addr: 'E210.7', label: 'RCH' },
  { addr: 'E211.0', label: 'FTXV' },
  { addr: 'E211.1', label: 'FTXH' },
  { addr: 'E211.2', label: '' },
  { addr: 'E211.3', label: 'EM' },
  { addr: 'E211.4', label: 'EHP1' },
  { addr: 'E211.5', label: 'EHP2' },
  { addr: 'E211.6', label: 'FTAC' },
  { addr: 'E211.7', label: 'EXD' },
  { addr: 'E212.0', label: 'AD' },
  { addr: 'E212.1', label: 'MTC' },
  { addr: 'E212.2', label: 'TCR' },
  { addr: 'E212.3', label: '' },
  { addr: 'E212.4', label: '' },
  { addr: 'E212.5', label: '' },
  { addr: 'E212.6', label: '' },
  { addr: 'E212.7', label: '' }
]
exports.inputs6 = [
  { addr: 'E4.0', label: '' },
  { addr: 'E4.1', label: '' },
  { addr: 'E4.2', label: '' },
  { addr: 'E4.3', label: '' },
  { addr: 'E4.4', label: '' },
  { addr: 'E4.5', label: '' },
  { addr: 'E4.6', label: '' },
  { addr: 'E4.7', label: '' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'LKU' },
  { addr: 'A0.1', label: 'LEU' },
  { addr: 'A0.2', label: 'LBU' },
  { addr: 'A0.3', label: 'RDY' },
  { addr: 'A0.4', label: 'RST' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: 'LA' },
  { addr: 'A0.7', label: 'RBU' },
  { addr: 'A1.0', label: '' },
  { addr: 'A1.1', label: '' },
  { addr: 'A1.2', label: '' },
  { addr: 'A1.3', label: '' },
  { addr: 'A1.4', label: '' },
  { addr: 'A1.5', label: '' },
  { addr: 'A1.6', label: 'LSA1' },
  { addr: 'A1.7', label: 'LSB2' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: 'SQA' },
  { addr: 'A100.1', label: 'KBA' },
  { addr: 'A100.2', label: 'SBK1' },
  { addr: 'A100.3', label: 'KXPE' },
  { addr: 'A100.4', label: 'SZE' },
  { addr: 'A100.5', label: 'SOE' },
  { addr: 'A100.6', label: 'LA' },
  { addr: 'A100.7', label: 'LC' },
  { addr: 'A101.0', label: 'L1' },
  { addr: 'A101.1', label: 'L2' },
  { addr: 'A101.2', label: 'L3' },
  { addr: 'A101.3', label: 'L4' },
  { addr: 'A101.4', label: 'L5' },
  { addr: 'A101.5', label: 'RFE' },
  { addr: 'A101.6', label: 'RLN' },
  { addr: 'A101.7', label: 'RBE' },
  { addr: 'A102.0', label: 'SMA1' },
  { addr: 'A102.1', label: 'SMB1' },
  { addr: 'A102.2', label: 'SMA2' },
  { addr: 'A102.3', label: 'SMB2' },
  { addr: 'A102.4', label: 'SCA' },
  { addr: 'A102.5', label: 'SCB' },
  { addr: 'A102.6', label: '' },
  { addr: 'A102.7', label: 'SPE' },
  { addr: 'A103.0', label: 'LK' },
  { addr: 'A103.1', label: 'LE' },
  { addr: 'A103.2', label: 'LB' },
  { addr: 'A103.3', label: 'RDY' },
  { addr: 'A103.4', label: 'RST' },
  { addr: 'A103.5', label: 'SBK2' },
  { addr: 'A103.6', label: 'TLIV' },
  { addr: 'A103.7', label: 'KEM' },
  { addr: 'A104.0', label: 'A' },
  { addr: 'A104.1', label: 'B' },
  { addr: 'A104.2', label: 'C' },
  { addr: 'A104.3', label: 'D' },
  { addr: 'A104.4', label: 'AD1' },
  { addr: 'A104.5', label: 'AD2' },
  { addr: 'A104.6', label: 'AD3' },
  { addr: 'A104.7', label: 'STR' },
  { addr: 'A105.0', label: 'SZE2' },
  { addr: 'A105.1', label: 'SOE2' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A110.0', label: 'T10' },
  { addr: 'A110.1', label: 'T2' },
  { addr: 'A110.2', label: 'TRA' },
  { addr: 'A110.3', label: 'TRB' },
  { addr: 'A110.4', label: 'TCR' },
  { addr: 'A110.5', label: '' },
  { addr: 'A110.6', label: '' },
  { addr: 'A110.7', label: '' },
  { addr: 'A111.0', label: 'TD' },
  { addr: 'A111.1', label: '' },
  { addr: 'A111.2', label: 'KCS' },
  { addr: 'A111.3', label: 'KCV' },
  { addr: 'A111.4', label: 'KCH' },
  { addr: 'A111.5', label: '' },
  { addr: 'A111.6', label: '' },
  { addr: 'A111.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A200.0', label: 'SQA' },
  { addr: 'A200.1', label: 'KBA' },
  { addr: 'A200.2', label: 'SBK1' },
  { addr: 'A200.3', label: 'KXPE' },
  { addr: 'A200.4', label: 'SZE' },
  { addr: 'A200.5', label: 'SOE' },
  { addr: 'A200.6', label: 'LA' },
  { addr: 'A200.7', label: 'LC' },
  { addr: 'A201.0', label: 'L1' },
  { addr: 'A201.1', label: 'L2' },
  { addr: 'A201.2', label: 'L3' },
  { addr: 'A201.3', label: 'L4' },
  { addr: 'A201.4', label: 'L5' },
  { addr: 'A201.5', label: 'RFE' },
  { addr: 'A201.6', label: 'RLN' },
  { addr: 'A201.7', label: 'RBE' },
  { addr: 'A202.0', label: 'SMA1' },
  { addr: 'A202.1', label: 'SMB1' },
  { addr: 'A202.2', label: 'SMA2' },
  { addr: 'A202.3', label: 'SMB2' },
  { addr: 'A202.4', label: 'SCA' },
  { addr: 'A202.5', label: 'SCB' },
  { addr: 'A202.6', label: '' },
  { addr: 'A202.7', label: 'SPE' },
  { addr: 'A203.0', label: 'LK' },
  { addr: 'A203.1', label: 'LE' },
  { addr: 'A203.2', label: 'LB' },
  { addr: 'A203.3', label: 'RDY' },
  { addr: 'A203.4', label: 'RST' },
  { addr: 'A203.5', label: 'SBK2' },
  { addr: 'A203.6', label: 'TLIV' },
  { addr: 'A203.7', label: 'KEM' },
  { addr: 'A204.0', label: 'A' },
  { addr: 'A204.1', label: 'B' },
  { addr: 'A204.2', label: 'C' },
  { addr: 'A204.3', label: 'D' },
  { addr: 'A204.4', label: 'AD1' },
  { addr: 'A204.5', label: 'AD2' },
  { addr: 'A204.6', label: 'AD3' },
  { addr: 'A204.7', label: 'STR' },
  { addr: 'A205.0', label: 'SZE2' },
  { addr: 'A205.1', label: 'SOE2' },
  { addr: 'A205.2', label: '' },
  { addr: 'A205.3', label: '' },
  { addr: 'A205.4', label: '' },
  { addr: 'A205.5', label: '' },
  { addr: 'A205.6', label: '' },
  { addr: 'A205.7', label: '' }
]
exports.outputs5 = [
  { addr: 'A210.0', label: 'T10' },
  { addr: 'A210.1', label: 'T2' },
  { addr: 'A210.2', label: 'TRA' },
  { addr: 'A210.3', label: 'TRB' },
  { addr: 'A210.4', label: 'TCR' },
  { addr: 'A210.5', label: '' },
  { addr: 'A210.6', label: '' },
  { addr: 'A210.7', label: '' },
  { addr: 'A211.0', label: 'TD' },
  { addr: 'A211.1', label: '' },
  { addr: 'A211.2', label: 'KCS' },
  { addr: 'A211.3', label: 'KCV' },
  { addr: 'A211.4', label: 'KCH' },
  { addr: 'A211.5', label: '' },
  { addr: 'A211.6', label: '' },
  { addr: 'A211.7', label: '' }
]
exports.outputs6 = [
  { addr: 'A4.0', label: '' },
  { addr: 'A4.1', label: '' },
  { addr: 'A4.2', label: '' },
  { addr: 'A4.3', label: '' },
  { addr: 'A4.4', label: '' },
  { addr: 'A4.5', label: '' },
  { addr: 'A4.6', label: '' },
  { addr: 'A4.7', label: '' }
]
exports.merkers = [
  { addr: 'M0.0', label: '' },
  { addr: 'M0.1', label: '' },
  { addr: 'M0.2', label: '' },
  { addr: 'M0.3', label: '' },
  { addr: 'M0.4', label: '' },
  { addr: 'M0.5', label: '' },
  { addr: 'M0.6', label: '' },
  { addr: 'M0.7', label: '' },
  { addr: 'M1.0', label: '' },
  { addr: 'M1.1', label: '' },
  { addr: 'M1.2', label: '' },
  { addr: 'M1.3', label: '' },
  { addr: 'M1.4', label: '' },
  { addr: 'M1.5', label: '' },
  { addr: 'M1.6', label: '' },
  { addr: 'M1.7', label: '' },
  { addr: 'M2.0', label: '' },
  { addr: 'M2.1', label: '' },
  { addr: 'M2.2', label: '' },
  { addr: 'M2.3', label: '' },
  { addr: 'M2.4', label: '' },
  { addr: 'M2.5', label: '' },
  { addr: 'M2.6', label: '' },
  { addr: 'M2.7', label: '' },
  { addr: 'M3.0', label: '' },
  { addr: 'M3.1', label: '' },
  { addr: 'M3.2', label: '' },
  { addr: 'M3.3', label: '' },
  { addr: 'M3.4', label: '' },
  { addr: 'M3.5', label: '' },
  { addr: 'M3.6', label: '' },
  { addr: 'M3.7', label: '' },
  { addr: 'M4.0', label: '' },
  { addr: 'M4.1', label: '' },
  { addr: 'M4.2', label: '' },
  { addr: 'M4.3', label: '' },
  { addr: 'M4.4', label: '' },
  { addr: 'M4.5', label: '' },
  { addr: 'M4.6', label: '' },
  { addr: 'M4.7', label: '' },
  { addr: 'M5.0', label: '' },
  { addr: 'M5.1', label: '' },
  { addr: 'M5.2', label: '' },
  { addr: 'M5.3', label: '' },
  { addr: 'M5.4', label: '' },
  { addr: 'M5.5', label: '' },
  { addr: 'M5.6', label: '' },
  { addr: 'M5.7', label: '' },
  { addr: 'M6.0', label: '' },
  { addr: 'M6.1', label: '' },
  { addr: 'M6.2', label: '' },
  { addr: 'M6.3', label: '' },
  { addr: 'M6.4', label: '' },
  { addr: 'M6.5', label: '' },
  { addr: 'M6.6', label: '' },
  { addr: 'M6.7', label: '' },
  { addr: 'M7.0', label: '' },
  { addr: 'M7.1', label: '' },
  { addr: 'M7.2', label: '' },
  { addr: 'M7.3', label: '' },
  { addr: 'M7.4', label: '' },
  { addr: 'M7.5', label: '' },
  { addr: 'M7.6', label: '' },
  { addr: 'M7.7', label: '' }
]

exports.alarms1 = [
  { class: 'SH1', label: 'AL1', info: 'Silomat travelling time out' },
  { class: 'SH1', label: 'AL2', info: 'Silomat hoisting time out' },
  { class: 'SH1', label: 'AL3', info: 'Silomat front centering time out' },
  { class: 'SH1', label: 'AL4', info: 'Silomat back centering time out' },
  { class: 'SH1', label: 'AL5', info: 'Silomat sensors MV/MH check (RG)' },
  { class: 'SH1', label: 'AL6', info: 'Silomat sensors MV/MH check (RL)' },
  { class: 'SH1', label: 'AL7', info: 'Silomat limitswitches ES/EH' },
  { class: 'SH1', label: 'AL8', info: 'Silomat limitswitches EBV/EAV' },
  { class: 'SH1', label: 'AL9', info: 'Silomat limitswitches EBH/EAH' },
  { class: 'SH1', label: 'AL10', info: 'Silomat cycle check (XG1)' },
  { class: 'SH1', label: 'AL11', info: 'Silomat centering' },
  { class: 'SH1', label: 'AL12', info: 'Silomat cycle check (XG2)' },
  { class: 'SH1', label: 'AL13', info: 'Silomat cycle check (FTXV/FTXH)' },
  { class: 'SH1', label: 'AL14', info: 'Silomat sensors MV/MH check (RL2)' },
  { class: 'SH1', label: 'AL15', info: 'Silomat cable-reel' },
  { class: 'SH1', label: 'AL16', info: '' },
  { class: 'SH1', label: 'AL17', info: 'Shuttle travelling time out' },
  { class: 'SH1', label: 'AL18', info: 'Horizontal laser not ready' },
  { class: 'SH1', label: 'AL19', info: 'Horizontal laser diversity check' },
  { class: 'SH1', label: 'AL20', info: 'Rotation time out' },
  { class: 'SH1', label: 'AL21', info: 'Rotation encoder out of range' },
  { class: 'SH1', label: 'AL22', info: '' },
  { class: 'SH1', label: 'AL23', info: '' },
  { class: 'SH1', label: 'AL24', info: '' },
  { class: 'SH1', label: 'AL25', info: '' },
  { class: 'SH1', label: 'AL26', info: '' },
  { class: 'SH1', label: 'AL27', info: '' },
  { class: 'SH1', label: 'AL28', info: '' },
  { class: 'SH1', label: 'AL29', info: '' },
  { class: 'SH1', label: 'AL30', info: '' },
  { class: 'SH1', label: 'AL31', info: '' },
  { class: 'SH1', label: 'AL32', info: '' },
  { class: 'SH1', label: 'AL33', info: '' },
  { class: 'SH1', label: 'AL34', info: '' },
  { class: 'SH1', label: 'AL35', info: '' },
  { class: 'SH1', label: 'AL36', info: '' },
  { class: 'SH1', label: 'AL37', info: '' },
  { class: 'SH1', label: 'AL38', info: '' },
  { class: 'SH1', label: 'AL39', info: '' },
  { class: 'SH1', label: 'AL40', info: '' },
  { class: 'SH1', label: 'AL41', info: '' },
  { class: 'SH1', label: 'AL42', info: '' },
  { class: 'SH1', label: 'AL43', info: '' },
  { class: 'SH1', label: 'AL44', info: '' },
  { class: 'SH1', label: 'AL45', info: '' },
  { class: 'SH1', label: 'AL46', info: '' },
  { class: 'SH1', label: 'AL47', info: '' },
  { class: 'SH1', label: 'AL48', info: '' },
  { class: 'SH1', label: 'AL49', info: 'Thermic AD' },
  { class: 'SH1', label: 'AL50', info: 'Thermic MTC' },
  { class: 'SH1', label: 'AL51', info: '' },
  { class: 'SH1', label: 'AL52', info: '' },
  { class: 'SH1', label: 'AL53', info: '' },
  { class: 'SH1', label: 'AL54', info: '' },
  { class: 'SH1', label: 'AL55', info: '' },
  { class: 'SH1', label: 'AL56', info: '' },
  { class: 'SH1', label: 'AL57', info: '' },
  { class: 'SH1', label: 'AL58', info: '' },
  { class: 'SH1', label: 'AL59', info: '' },
  { class: 'SH1', label: 'AL60', info: '' },
  { class: 'SH1', label: 'AL61', info: '' },
  { class: 'SH1', label: 'AL62', info: '' },
  { class: 'SH1', label: 'AL63', info: '' },
  { class: 'SH1', label: 'AL64', info: '' }
]
