exports.devices = ['EL1', 'EL2', 'EL3', 'T1', 'T2', 'T3']

exports.garages = ['VG1', 'VG2', 'VG3']

exports.modes = [
  'mode-no-func',
  'mode-data-edit',
  'mode-data-read',
  'mode-eme-1',
  'mode-eme-2',
  'mode-no-func',
  'mode-step',
  'mode-preset',
  'mode-auto'
]

exports.operations = [
  '---',
  'op-alarm-on',
  'op-alarm-off',
  'op-switch-mode',
  'op-change-pin',
  'op-stall-in',
  'op-stall-out',
  'op-shuffle-in',
  'op-shuffle-out',
  'op-stall-rsv',
  'op-req-exit',
  'op-req-entry',
  '---',
  '---',
  '---',
  '---'
]

exports.positions = [
  'Laser V1',
  'Laser V2',
  'Laser H1',
  'Laser H2',
  'Laser V1',
  'Laser V2',
  'Laser H1',
  'Laser H2',
  'Laser V1',
  'Laser V2',
  'Laser H1',
  'Laser H2',
  'Laser V',
  'Encoder R',
  'Laser V',
  'Encoder R',
  'Laser V',
  'Encoder R'
]

exports.drives = [
  'IV1-T1',
  'IV2-T1',
  'IV1-T2',
  'IV2-T2',
  'IV1-T3',
  'IV2-T3',
  'IV-A',
  'IV-B',
  'IV-C'
]

exports.inputs1 = [
  { addr: 'E0.0', label: 'BA' },
  { addr: 'E0.1', label: 'BB' },
  { addr: 'E0.2', label: 'BC' },
  { addr: 'E0.3', label: 'BD' },
  { addr: 'E0.4', label: 'BSTR' },
  { addr: 'E0.5', label: 'BOK' },
  { addr: 'E0.6', label: 'BDAT' },
  { addr: 'E0.7', label: '' },
  { addr: 'E1.0', label: 'BA' },
  { addr: 'E1.1', label: 'BB' },
  { addr: 'E1.2', label: 'BC' },
  { addr: 'E1.3', label: 'BD' },
  { addr: 'E1.4', label: 'BSTR' },
  { addr: 'E1.5', label: 'BOK' },
  { addr: 'E1.6', label: 'BDAT' },
  { addr: 'E1.7', label: '' },
  { addr: 'E2.0', label: 'SFA' },
  { addr: 'E2.1', label: 'SFB' },
  { addr: 'E2.2', label: 'SFC' },
  { addr: 'E2.3', label: 'SFT1' },
  { addr: 'E2.4', label: 'SFT2' },
  { addr: 'E2.5', label: 'SFT3' },
  { addr: 'E2.6', label: '' },
  { addr: 'E2.7', label: 'RSI' },
  { addr: 'E3.0', label: '' },
  { addr: 'E3.1', label: '' },
  { addr: 'E3.2', label: '' },
  { addr: 'E3.3', label: '' },
  { addr: 'E3.4', label: '' },
  { addr: 'E3.5', label: '' },
  { addr: 'E3.6', label: '' },
  { addr: 'E3.7', label: 'FE' }
]
exports.inputs2 = [
  { addr: 'E100.0', label: 'A' },
  { addr: 'E100.1', label: 'B' },
  { addr: 'E100.2', label: 'C' },
  { addr: 'E100.3', label: 'D' },
  { addr: 'E100.4', label: 'OK' },
  { addr: 'E100.5', label: 'S2' },
  { addr: 'E100.6', label: 'S2' },
  { addr: 'E100.7', label: 'S2' },
  { addr: 'E101.0', label: 'A' },
  { addr: 'E101.1', label: 'B' },
  { addr: 'E101.2', label: 'C' },
  { addr: 'E101.3', label: 'D' },
  { addr: 'E101.4', label: 'STR' },
  { addr: 'E101.5', label: 'OK' },
  { addr: 'E101.6', label: 'DAT' },
  { addr: 'E101.7', label: '' },
  { addr: 'E102.0', label: 'KEXPV' },
  { addr: 'E102.1', label: 'FTC' },
  { addr: 'E102.2', label: 'EXPV' },
  { addr: 'E102.3', label: 'EFB' },
  { addr: 'E102.4', label: 'ECA' },
  { addr: 'E102.5', label: 'ECB' },
  { addr: 'E102.6', label: 'AMC' },
  { addr: 'E102.7', label: 'APE' },
  { addr: 'E103.0', label: 'FTXV' },
  { addr: 'E103.1', label: 'FTXH' },
  { addr: 'E103.2', label: 'RS3' },
  { addr: 'E103.3', label: 'RS12' },
  { addr: 'E103.4', label: 'DB32' },
  { addr: 'E103.5', label: 'DBHZ' },
  { addr: 'E103.6', label: 'KXPE' },
  { addr: 'E103.7', label: 'AF7' },
  { addr: 'E104.0', label: 'FKBA' },
  { addr: 'E104.1', label: 'ASBK2' },
  { addr: 'E104.2', label: 'SRL' },
  { addr: 'E104.3', label: 'IV1' },
  { addr: 'E104.4', label: 'FSBK' },
  { addr: 'E104.5', label: 'ASBK1' },
  { addr: 'E104.6', label: 'RTA' },
  { addr: 'E104.7', label: 'SQA' },
  { addr: 'E105.0', label: 'FE12' },
  { addr: 'E105.1', label: 'AD' },
  { addr: 'E105.2', label: 'EXD' },
  { addr: 'E105.3', label: 'EOM' },
  { addr: 'E105.4', label: 'EZM' },
  { addr: 'E105.5', label: 'AMM' },
  { addr: 'E105.6', label: '' },
  { addr: 'E105.7', label: '' },
  { addr: 'E106.0', label: 'EZE' },
  { addr: 'E106.1', label: 'EOE' },
  { addr: 'E106.2', label: 'FBE' },
  { addr: 'E106.3', label: 'FPE' },
  { addr: 'E106.4', label: 'FDR1' },
  { addr: 'E106.5', label: 'FDL1' },
  { addr: 'E106.6', label: 'FTA1' },
  { addr: 'E106.7', label: 'FTA2' },
  { addr: 'E107.0', label: 'FLP1' },
  { addr: 'E107.1', label: 'FLP2' },
  { addr: 'E107.2', label: 'FLA' },
  { addr: 'E107.3', label: '' },
  { addr: 'E107.4', label: '' },
  { addr: 'E107.5', label: 'FRE' },
  { addr: 'E107.6', label: 'RX1' },
  { addr: 'E107.7', label: 'RX2' },
  { addr: 'E108.0', label: 'EOMD' },
  { addr: 'E108.1', label: 'EZMD' },
  { addr: 'E108.2', label: 'AMD' },
  { addr: 'E108.3', label: 'SPR' },
  { addr: 'E108.4', label: '' },
  { addr: 'E108.5', label: '' },
  { addr: 'E108.6', label: '' },
  { addr: 'E108.7', label: '' },
  { addr: 'E109.0', label: '' },
  { addr: 'E109.1', label: '' },
  { addr: 'E109.2', label: '' },
  { addr: 'E109.3', label: '' },
  { addr: 'E109.4', label: '' },
  { addr: 'E109.5', label: '' },
  { addr: 'E109.6', label: '' },
  { addr: 'E109.7', label: '' }
]
exports.inputs3 = [
  { addr: 'E200.0', label: 'A' },
  { addr: 'E200.1', label: 'B' },
  { addr: 'E200.2', label: 'C' },
  { addr: 'E200.3', label: 'D' },
  { addr: 'E200.4', label: 'OK' },
  { addr: 'E200.5', label: 'S2' },
  { addr: 'E200.6', label: 'S2' },
  { addr: 'E200.7', label: 'S2' },
  { addr: 'E201.0', label: 'A' },
  { addr: 'E201.1', label: 'B' },
  { addr: 'E201.2', label: 'C' },
  { addr: 'E201.3', label: 'D' },
  { addr: 'E201.4', label: 'STR' },
  { addr: 'E201.5', label: 'OK' },
  { addr: 'E201.6', label: 'DAT' },
  { addr: 'E201.7', label: '' },
  { addr: 'E202.0', label: 'KEXPV' },
  { addr: 'E202.1', label: 'FTC' },
  { addr: 'E202.2', label: 'EXPV' },
  { addr: 'E202.3', label: 'EFB' },
  { addr: 'E202.4', label: 'ECA' },
  { addr: 'E202.5', label: 'ECB' },
  { addr: 'E202.6', label: 'AMC' },
  { addr: 'E202.7', label: 'APE' },
  { addr: 'E203.0', label: 'FTXV' },
  { addr: 'E203.1', label: 'FTXH' },
  { addr: 'E203.2', label: 'RS3' },
  { addr: 'E203.3', label: 'RS12' },
  { addr: 'E203.4', label: 'DB32' },
  { addr: 'E203.5', label: 'DBHZ' },
  { addr: 'E203.6', label: 'KXPE' },
  { addr: 'E203.7', label: 'AF7' },
  { addr: 'E204.0', label: 'FKBA' },
  { addr: 'E204.1', label: 'ASBK2' },
  { addr: 'E204.2', label: 'SRL' },
  { addr: 'E204.3', label: 'IV1' },
  { addr: 'E204.4', label: 'FSBK' },
  { addr: 'E204.5', label: 'ASBK1' },
  { addr: 'E204.6', label: 'RTA' },
  { addr: 'E204.7', label: 'SQA' },
  { addr: 'E205.0', label: 'FE12' },
  { addr: 'E205.1', label: 'AD' },
  { addr: 'E205.2', label: 'EXD' },
  { addr: 'E205.3', label: 'EOM' },
  { addr: 'E205.4', label: 'EZM' },
  { addr: 'E205.5', label: 'AMM' },
  { addr: 'E205.6', label: '' },
  { addr: 'E205.7', label: '' },
  { addr: 'E206.0', label: 'EZE' },
  { addr: 'E206.1', label: 'EOE' },
  { addr: 'E206.2', label: 'FBE' },
  { addr: 'E206.3', label: 'FPE' },
  { addr: 'E206.4', label: 'FDR1' },
  { addr: 'E206.5', label: 'FDL1' },
  { addr: 'E206.6', label: 'FTA1' },
  { addr: 'E206.7', label: 'FTA2' },
  { addr: 'E207.0', label: 'FLP1' },
  { addr: 'E207.1', label: 'FLP2' },
  { addr: 'E207.2', label: 'FLA' },
  { addr: 'E207.3', label: '' },
  { addr: 'E207.4', label: '' },
  { addr: 'E207.5', label: 'FRE' },
  { addr: 'E207.6', label: 'RX1' },
  { addr: 'E207.7', label: 'RX2' },
  { addr: 'E208.0', label: 'EOMD' },
  { addr: 'E208.1', label: 'EZMD' },
  { addr: 'E208.2', label: 'AMD' },
  { addr: 'E208.3', label: 'SPR' },
  { addr: 'E208.4', label: '' },
  { addr: 'E208.5', label: '' },
  { addr: 'E208.6', label: '' },
  { addr: 'E208.7', label: '' },
  { addr: 'E209.0', label: '' },
  { addr: 'E209.1', label: '' },
  { addr: 'E209.2', label: '' },
  { addr: 'E209.3', label: '' },
  { addr: 'E209.4', label: '' },
  { addr: 'E209.5', label: '' },
  { addr: 'E209.6', label: '' },
  { addr: 'E209.7', label: '' }
]
exports.inputs4 = [
  { addr: 'E300.0', label: 'A' },
  { addr: 'E300.1', label: 'B' },
  { addr: 'E300.2', label: 'C' },
  { addr: 'E300.3', label: 'D' },
  { addr: 'E300.4', label: 'OK' },
  { addr: 'E300.5', label: 'S2' },
  { addr: 'E300.6', label: 'S2' },
  { addr: 'E300.7', label: 'S2' },
  { addr: 'E301.0', label: 'BA' },
  { addr: 'E301.1', label: 'BB' },
  { addr: 'E301.2', label: 'BC' },
  { addr: 'E301.3', label: 'BD' },
  { addr: 'E301.4', label: 'BSTR' },
  { addr: 'E301.5', label: 'BOK' },
  { addr: 'E301.6', label: 'BDAT' },
  { addr: 'E301.7', label: 'UC' },
  { addr: 'E302.0', label: 'KEXPV' },
  { addr: 'E302.1', label: 'FTC' },
  { addr: 'E302.2', label: 'EXPV' },
  { addr: 'E302.3', label: 'EFB' },
  { addr: 'E302.4', label: 'ECA' },
  { addr: 'E302.5', label: 'ECB' },
  { addr: 'E302.6', label: 'AMC' },
  { addr: 'E302.7', label: 'APE' },
  { addr: 'E303.0', label: 'FTXV' },
  { addr: 'E303.1', label: 'FTXH' },
  { addr: 'E303.2', label: 'RS3' },
  { addr: 'E303.3', label: 'RS12' },
  { addr: 'E303.4', label: 'DB32' },
  { addr: 'E303.5', label: 'DBHZ' },
  { addr: 'E303.6', label: 'KXPE' },
  { addr: 'E303.7', label: 'AF7' },
  { addr: 'E304.0', label: 'FKBA' },
  { addr: 'E304.1', label: 'ASBK2' },
  { addr: 'E304.2', label: 'SRL' },
  { addr: 'E304.3', label: 'IV1' },
  { addr: 'E304.4', label: 'FSBK' },
  { addr: 'E304.5', label: 'ASBK1' },
  { addr: 'E304.6', label: 'RTA' },
  { addr: 'E304.7', label: 'SQA' },
  { addr: 'E305.0', label: 'FE12' },
  { addr: 'E305.1', label: 'AD' },
  { addr: 'E305.2', label: 'EXD' },
  { addr: 'E305.3', label: 'EOM' },
  { addr: 'E305.4', label: 'EZM' },
  { addr: 'E305.5', label: 'AMM' },
  { addr: 'E305.6', label: '' },
  { addr: 'E305.7', label: '' },
  { addr: 'E306.0', label: 'EZE' },
  { addr: 'E306.1', label: 'EOE' },
  { addr: 'E306.2', label: 'FBE' },
  { addr: 'E306.3', label: 'FPE' },
  { addr: 'E306.4', label: 'FDR1' },
  { addr: 'E306.5', label: 'FDL1' },
  { addr: 'E306.6', label: 'FTA1' },
  { addr: 'E306.7', label: 'FTA2' },
  { addr: 'E307.0', label: 'FLP1' },
  { addr: 'E307.1', label: 'FLP2' },
  { addr: 'E307.2', label: 'FLA' },
  { addr: 'E307.3', label: '' },
  { addr: 'E307.4', label: '' },
  { addr: 'E307.5', label: 'FRE' },
  { addr: 'E307.6', label: 'RX1' },
  { addr: 'E307.7', label: 'RX2' },
  { addr: 'E308.0', label: 'EOMD' },
  { addr: 'E308.1', label: 'EZMD' },
  { addr: 'E308.2', label: 'AMD' },
  { addr: 'E308.3', label: 'SPR' },
  { addr: 'E308.4', label: '' },
  { addr: 'E308.5', label: '' },
  { addr: 'E308.6', label: '' },
  { addr: 'E308.7', label: '' },
  { addr: 'E309.0', label: '' },
  { addr: 'E309.1', label: '' },
  { addr: 'E309.2', label: '' },
  { addr: 'E309.3', label: '' },
  { addr: 'E309.4', label: '' },
  { addr: 'E309.5', label: '' },
  { addr: 'E309.6', label: '' },
  { addr: 'E309.7', label: '' }
]
exports.inputs5 = [
  { addr: 'E400.0', label: 'FTACR' },
  { addr: 'E400.1', label: '' },
  { addr: 'E400.2', label: 'FTACL' },
  { addr: 'E400.3', label: '' },
  { addr: 'E400.4', label: '' },
  { addr: 'E400.5', label: '' },
  { addr: 'E400.6', label: 'FE1' },
  { addr: 'E400.7', label: 'AF7' },
  { addr: 'E401.0', label: 'IV1' },
  { addr: 'E401.1', label: 'IV2' },
  { addr: 'E401.2', label: '' },
  { addr: 'E401.3', label: 'RS12' },
  { addr: 'E401.4', label: 'RS3' },
  { addr: 'E401.5', label: 'AH' },
  { addr: 'E401.6', label: 'AGF' },
  { addr: 'E401.7', label: 'AKKP' }
]
exports.inputs6 = [
  { addr: 'E410.0', label: 'A' },
  { addr: 'E410.1', label: 'B' },
  { addr: 'E410.2', label: 'C' },
  { addr: 'E410.3', label: 'D' },
  { addr: 'E410.4', label: 'OK' },
  { addr: 'E410.5', label: 'S2' },
  { addr: 'E410.6', label: 'S2' },
  { addr: 'E410.7', label: 'S2' },
  { addr: 'E411.0', label: 'EM' },
  { addr: 'E411.1', label: 'EXPV' },
  { addr: 'E411.2', label: 'FSBK' },
  { addr: 'E411.3', label: 'ASBK1' },
  { addr: 'E411.4', label: 'FTCR' },
  { addr: 'E411.5', label: 'AGH' },
  { addr: 'E411.6', label: 'FTXV' },
  { addr: 'E411.7', label: 'FTXH' },
  { addr: 'E412.0', label: 'RMV' },
  { addr: 'E412.1', label: 'RMH' },
  { addr: 'E412.2', label: 'RES' },
  { addr: 'E412.3', label: 'REH' },
  { addr: 'E412.4', label: 'RCV' },
  { addr: 'E412.5', label: 'REAV' },
  { addr: 'E412.6', label: 'REAH' },
  { addr: 'E412.7', label: 'RCH' },
  { addr: 'E413.0', label: '' },
  { addr: 'E413.1', label: '' },
  { addr: 'E413.2', label: 'SRL' },
  { addr: 'E413.3', label: '' },
  { addr: 'E413.4', label: 'DB32' },
  { addr: 'E413.5', label: 'DBHZ' },
  { addr: 'E413.6', label: 'FTM' },
  { addr: 'E413.7', label: 'UC' }
]
exports.inputs7 = [
  { addr: 'E500.0', label: 'FTACR' },
  { addr: 'E500.1', label: '' },
  { addr: 'E500.2', label: 'FTACL' },
  { addr: 'E500.3', label: '' },
  { addr: 'E500.4', label: '' },
  { addr: 'E500.5', label: '' },
  { addr: 'E500.6', label: 'FE1' },
  { addr: 'E500.7', label: 'AF7' },
  { addr: 'E501.0', label: 'IV1' },
  { addr: 'E501.1', label: 'IV2' },
  { addr: 'E501.2', label: '' },
  { addr: 'E501.3', label: 'RS12' },
  { addr: 'E501.4', label: 'RS3' },
  { addr: 'E501.5', label: 'AH' },
  { addr: 'E501.6', label: 'AGF' },
  { addr: 'E501.7', label: 'AKKP' }
]
exports.inputs8 = [
  { addr: 'E510.0', label: 'A' },
  { addr: 'E510.1', label: 'B' },
  { addr: 'E510.2', label: 'C' },
  { addr: 'E510.3', label: 'D' },
  { addr: 'E510.4', label: 'OK' },
  { addr: 'E510.5', label: 'S2' },
  { addr: 'E510.6', label: 'S2' },
  { addr: 'E510.7', label: 'S2' },
  { addr: 'E511.0', label: 'EM' },
  { addr: 'E511.1', label: 'EXPV' },
  { addr: 'E511.2', label: 'FSBK' },
  { addr: 'E511.3', label: 'ASBK1' },
  { addr: 'E511.4', label: 'FTCR' },
  { addr: 'E511.5', label: 'AGH' },
  { addr: 'E511.6', label: 'FTXV' },
  { addr: 'E511.7', label: 'FTXH' },
  { addr: 'E512.0', label: 'RMV' },
  { addr: 'E512.1', label: 'RMH' },
  { addr: 'E512.2', label: 'RES' },
  { addr: 'E512.3', label: 'REH' },
  { addr: 'E512.4', label: 'RCV' },
  { addr: 'E512.5', label: 'REAV' },
  { addr: 'E512.6', label: 'REAH' },
  { addr: 'E512.7', label: 'RCH' },
  { addr: 'E513.0', label: '' },
  { addr: 'E513.1', label: '' },
  { addr: 'E513.2', label: 'SRL' },
  { addr: 'E513.3', label: '' },
  { addr: 'E513.4', label: 'DB32' },
  { addr: 'E513.5', label: 'DBHZ' },
  { addr: 'E513.6', label: 'FTM' },
  { addr: 'E513.7', label: 'UC' }
]
exports.inputs9 = [
  { addr: 'E600.0', label: 'FTACR' },
  { addr: 'E600.1', label: '' },
  { addr: 'E600.2', label: 'FTACL' },
  { addr: 'E600.3', label: '' },
  { addr: 'E600.4', label: '' },
  { addr: 'E600.5', label: '' },
  { addr: 'E600.6', label: 'FE1' },
  { addr: 'E600.7', label: 'AF7' },
  { addr: 'E601.0', label: 'IV1' },
  { addr: 'E601.1', label: 'IV2' },
  { addr: 'E601.2', label: '' },
  { addr: 'E601.3', label: 'RS12' },
  { addr: 'E601.4', label: 'RS3' },
  { addr: 'E601.5', label: 'AH' },
  { addr: 'E601.6', label: 'AGF' },
  { addr: 'E601.7', label: 'AKKP' }
]
exports.inputs10 = [
  { addr: 'E610.0', label: 'A' },
  { addr: 'E610.1', label: 'B' },
  { addr: 'E610.2', label: 'C' },
  { addr: 'E610.3', label: 'D' },
  { addr: 'E610.4', label: 'OK' },
  { addr: 'E610.5', label: 'S2' },
  { addr: 'E610.6', label: 'S2' },
  { addr: 'E610.7', label: 'S2' },
  { addr: 'E611.0', label: 'EM' },
  { addr: 'E611.1', label: 'EXPV' },
  { addr: 'E611.2', label: 'FSBK' },
  { addr: 'E611.3', label: 'ASBK1' },
  { addr: 'E611.4', label: 'FTCR' },
  { addr: 'E611.5', label: 'AGH' },
  { addr: 'E611.6', label: 'FTXV' },
  { addr: 'E611.7', label: 'FTXH' },
  { addr: 'E612.0', label: 'RMV' },
  { addr: 'E612.1', label: 'RMH' },
  { addr: 'E612.2', label: 'RES' },
  { addr: 'E612.3', label: 'REH' },
  { addr: 'E612.4', label: 'RCV' },
  { addr: 'E612.5', label: 'REAV' },
  { addr: 'E612.6', label: 'REAH' },
  { addr: 'E612.7', label: 'RCH' },
  { addr: 'E613.0', label: '' },
  { addr: 'E613.1', label: '' },
  { addr: 'E613.2', label: 'SRL' },
  { addr: 'E613.3', label: '' },
  { addr: 'E613.4', label: 'DB32' },
  { addr: 'E613.5', label: 'DBHZ' },
  { addr: 'E613.6', label: 'FTM' },
  { addr: 'E613.7', label: 'UC' }
]
exports.outputs1 = [
  { addr: 'A0.0', label: 'LK' },
  { addr: 'A0.1', label: 'LE' },
  { addr: 'A0.2', label: 'LB' },
  { addr: 'A0.3', label: 'RDY' },
  { addr: 'A0.4', label: 'RST' },
  { addr: 'A0.5', label: '' },
  { addr: 'A0.6', label: 'LA' },
  { addr: 'A0.7', label: 'RBU' },
  { addr: 'A1.0', label: 'LK' },
  { addr: 'A1.1', label: 'LE' },
  { addr: 'A1.2', label: 'LB' },
  { addr: 'A1.3', label: 'RDY' },
  { addr: 'A1.4', label: 'RST' },
  { addr: 'A1.5', label: 'LSA' },
  { addr: 'A1.6', label: 'LSB' },
  { addr: 'A1.7', label: 'LSC' },
  { addr: 'A2.0', label: '' },
  { addr: 'A2.1', label: '' },
  { addr: 'A2.2', label: '' },
  { addr: 'A2.3', label: '' },
  { addr: 'A2.4', label: '' },
  { addr: 'A2.5', label: 'LST1' },
  { addr: 'A2.6', label: 'LST2' },
  { addr: 'A2.7', label: 'LST3' },
  { addr: 'A3.0', label: '' },
  { addr: 'A3.1', label: '' },
  { addr: 'A3.2', label: '' },
  { addr: 'A3.3', label: '' },
  { addr: 'A3.4', label: '' },
  { addr: 'A3.5', label: '' },
  { addr: 'A3.6', label: '' },
  { addr: 'A3.7', label: '' }
]
exports.outputs2 = [
  { addr: 'A100.0', label: '' },
  { addr: 'A100.1', label: 'KBA' },
  { addr: 'A100.2', label: 'SBK1' },
  { addr: 'A100.3', label: 'KXPE' },
  { addr: 'A100.4', label: 'SZE' },
  { addr: 'A100.5', label: 'SOE' },
  { addr: 'A100.6', label: 'LA' },
  { addr: 'A100.7', label: 'LC' },
  { addr: 'A101.0', label: 'L1' },
  { addr: 'A101.1', label: 'L2' },
  { addr: 'A101.2', label: 'L3' },
  { addr: 'A101.3', label: 'L4' },
  { addr: 'A101.4', label: 'L5' },
  { addr: 'A101.5', label: 'RFE' },
  { addr: 'A101.6', label: 'RLN' },
  { addr: 'A101.7', label: 'RBE' },
  { addr: 'A102.0', label: 'SMA' },
  { addr: 'A102.1', label: 'SMB' },
  { addr: 'A102.2', label: 'KQA' },
  { addr: 'A102.3', label: '' },
  { addr: 'A102.4', label: 'SCA' },
  { addr: 'A102.5', label: 'SCB' },
  { addr: 'A102.6', label: 'TD' },
  { addr: 'A102.7', label: 'SPE' },
  { addr: 'A103.0', label: 'LK' },
  { addr: 'A103.1', label: 'LE' },
  { addr: 'A103.2', label: 'LB' },
  { addr: 'A103.3', label: 'RDY' },
  { addr: 'A103.4', label: 'RST' },
  { addr: 'A103.5', label: 'SBK2' },
  { addr: 'A103.6', label: '' },
  { addr: 'A103.7', label: 'KEM' },
  { addr: 'A104.0', label: 'DYA' },
  { addr: 'A104.1', label: 'DYB' },
  { addr: 'A104.2', label: 'DYC' },
  { addr: 'A104.3', label: 'DYD' },
  { addr: 'A104.4', label: 'AD1' },
  { addr: 'A104.5', label: 'AD2' },
  { addr: 'A104.6', label: 'AD3' },
  { addr: 'A104.7', label: 'STR' },
  { addr: 'A105.0', label: 'SMAD' },
  { addr: 'A105.1', label: 'SMBD' },
  { addr: 'A105.2', label: '' },
  { addr: 'A105.3', label: '' },
  { addr: 'A105.4', label: '' },
  { addr: 'A105.5', label: '' },
  { addr: 'A105.6', label: '' },
  { addr: 'A105.7', label: '' },
  { addr: 'A106.0', label: '' },
  { addr: 'A106.1', label: '' },
  { addr: 'A106.2', label: '' },
  { addr: 'A106.3', label: '' },
  { addr: 'A106.4', label: '' },
  { addr: 'A106.5', label: '' },
  { addr: 'A106.6', label: '' },
  { addr: 'A106.7', label: '' },
  { addr: 'A107.0', label: '' },
  { addr: 'A107.1', label: '' },
  { addr: 'A107.2', label: '' },
  { addr: 'A107.3', label: '' },
  { addr: 'A107.4', label: '' },
  { addr: 'A107.5', label: '' },
  { addr: 'A107.6', label: '' },
  { addr: 'A107.7', label: '' },
  { addr: 'A108.0', label: '' },
  { addr: 'A108.1', label: '' },
  { addr: 'A108.2', label: '' },
  { addr: 'A108.3', label: '' },
  { addr: 'A108.4', label: '' },
  { addr: 'A108.5', label: '' },
  { addr: 'A108.6', label: '' },
  { addr: 'A108.7', label: '' },
  { addr: 'A109.0', label: '' },
  { addr: 'A109.1', label: '' },
  { addr: 'A109.2', label: '' },
  { addr: 'A109.3', label: '' },
  { addr: 'A109.4', label: '' },
  { addr: 'A109.5', label: '' },
  { addr: 'A109.6', label: '' },
  { addr: 'A109.7', label: '' }
]
exports.outputs3 = [
  { addr: 'A200.0', label: '' },
  { addr: 'A200.1', label: 'KBA' },
  { addr: 'A200.2', label: 'SBK1' },
  { addr: 'A200.3', label: 'KXPE' },
  { addr: 'A200.4', label: 'SZE' },
  { addr: 'A200.5', label: 'SOE' },
  { addr: 'A200.6', label: 'LA' },
  { addr: 'A200.7', label: 'LC' },
  { addr: 'A201.0', label: 'L1' },
  { addr: 'A201.1', label: 'L2' },
  { addr: 'A201.2', label: 'L3' },
  { addr: 'A201.3', label: 'L4' },
  { addr: 'A201.4', label: 'L5' },
  { addr: 'A201.5', label: 'RFE' },
  { addr: 'A201.6', label: 'RLN' },
  { addr: 'A201.7', label: 'RBE' },
  { addr: 'A202.0', label: 'SMA' },
  { addr: 'A202.1', label: 'SMB' },
  { addr: 'A202.2', label: 'KQA' },
  { addr: 'A202.3', label: '' },
  { addr: 'A202.4', label: 'SCA' },
  { addr: 'A202.5', label: 'SCB' },
  { addr: 'A202.6', label: 'TD' },
  { addr: 'A202.7', label: 'SPE' },
  { addr: 'A203.0', label: 'LK' },
  { addr: 'A203.1', label: 'LE' },
  { addr: 'A203.2', label: 'LB' },
  { addr: 'A203.3', label: 'RDY' },
  { addr: 'A203.4', label: 'RST' },
  { addr: 'A203.5', label: 'SBK2' },
  { addr: 'A203.6', label: '' },
  { addr: 'A203.7', label: 'KEM' },
  { addr: 'A204.0', label: 'DYA' },
  { addr: 'A204.1', label: 'DYB' },
  { addr: 'A204.2', label: 'DYC' },
  { addr: 'A204.3', label: 'DYD' },
  { addr: 'A204.4', label: 'AD1' },
  { addr: 'A204.5', label: 'AD2' },
  { addr: 'A204.6', label: 'AD3' },
  { addr: 'A204.7', label: 'STR' },
  { addr: 'A205.0', label: 'SMAD' },
  { addr: 'A205.1', label: 'SMBD' },
  { addr: 'A205.2', label: '' },
  { addr: 'A205.3', label: '' },
  { addr: 'A205.4', label: '' },
  { addr: 'A205.5', label: '' },
  { addr: 'A205.6', label: '' },
  { addr: 'A205.7', label: '' },
  { addr: 'A206.0', label: '' },
  { addr: 'A206.1', label: '' },
  { addr: 'A206.2', label: '' },
  { addr: 'A206.3', label: '' },
  { addr: 'A206.4', label: '' },
  { addr: 'A206.5', label: '' },
  { addr: 'A206.6', label: '' },
  { addr: 'A206.7', label: '' },
  { addr: 'A207.0', label: '' },
  { addr: 'A207.1', label: '' },
  { addr: 'A207.2', label: '' },
  { addr: 'A207.3', label: '' },
  { addr: 'A207.4', label: '' },
  { addr: 'A207.5', label: '' },
  { addr: 'A207.6', label: '' },
  { addr: 'A207.7', label: '' },
  { addr: 'A208.0', label: '' },
  { addr: 'A208.1', label: '' },
  { addr: 'A208.2', label: '' },
  { addr: 'A208.3', label: '' },
  { addr: 'A208.4', label: '' },
  { addr: 'A208.5', label: '' },
  { addr: 'A208.6', label: '' },
  { addr: 'A208.7', label: '' },
  { addr: 'A209.0', label: '' },
  { addr: 'A209.1', label: '' },
  { addr: 'A209.2', label: '' },
  { addr: 'A209.3', label: '' },
  { addr: 'A209.4', label: '' },
  { addr: 'A209.5', label: '' },
  { addr: 'A209.6', label: '' },
  { addr: 'A209.7', label: '' }
]
exports.outputs4 = [
  { addr: 'A300.0', label: '' },
  { addr: 'A300.1', label: 'KBA' },
  { addr: 'A300.2', label: 'SBK1' },
  { addr: 'A300.3', label: 'KXPE' },
  { addr: 'A300.4', label: 'SZE' },
  { addr: 'A300.5', label: 'SOE' },
  { addr: 'A300.6', label: 'LA' },
  { addr: 'A300.7', label: 'LC' },
  { addr: 'A301.0', label: 'L1' },
  { addr: 'A301.1', label: 'L2' },
  { addr: 'A301.2', label: 'L3' },
  { addr: 'A301.3', label: 'L4' },
  { addr: 'A301.4', label: 'L5' },
  { addr: 'A301.5', label: 'RFE' },
  { addr: 'A301.6', label: 'RLN' },
  { addr: 'A301.7', label: 'RBE' },
  { addr: 'A302.0', label: 'SMA' },
  { addr: 'A302.1', label: 'SMB' },
  { addr: 'A302.2', label: 'KQA' },
  { addr: 'A302.3', label: '' },
  { addr: 'A302.4', label: 'SCA' },
  { addr: 'A302.5', label: 'SCB' },
  { addr: 'A302.6', label: 'TD' },
  { addr: 'A302.7', label: 'SPE' },
  { addr: 'A303.0', label: 'LK' },
  { addr: 'A303.1', label: 'LE' },
  { addr: 'A303.2', label: 'LB' },
  { addr: 'A303.3', label: 'RDY' },
  { addr: 'A303.4', label: 'RST' },
  { addr: 'A303.5', label: 'SBK2' },
  { addr: 'A303.6', label: '' },
  { addr: 'A303.7', label: 'KEM' },
  { addr: 'A304.0', label: 'DYA' },
  { addr: 'A304.1', label: 'DYB' },
  { addr: 'A304.2', label: 'DYC' },
  { addr: 'A304.3', label: 'DYD' },
  { addr: 'A304.4', label: 'AD1' },
  { addr: 'A304.5', label: 'AD2' },
  { addr: 'A304.6', label: 'AD3' },
  { addr: 'A304.7', label: 'STR' },
  { addr: 'A305.0', label: 'SMAD' },
  { addr: 'A305.1', label: 'SMBD' },
  { addr: 'A305.2', label: '' },
  { addr: 'A305.3', label: '' },
  { addr: 'A305.4', label: '' },
  { addr: 'A305.5', label: '' },
  { addr: 'A305.6', label: '' },
  { addr: 'A305.7', label: '' },
  { addr: 'A306.0', label: '' },
  { addr: 'A306.1', label: '' },
  { addr: 'A306.2', label: '' },
  { addr: 'A306.3', label: '' },
  { addr: 'A306.4', label: '' },
  { addr: 'A306.5', label: '' },
  { addr: 'A306.6', label: '' },
  { addr: 'A306.7', label: '' },
  { addr: 'A307.0', label: '' },
  { addr: 'A307.1', label: '' },
  { addr: 'A307.2', label: '' },
  { addr: 'A307.3', label: '' },
  { addr: 'A307.4', label: '' },
  { addr: 'A307.5', label: '' },
  { addr: 'A307.6', label: '' },
  { addr: 'A307.7', label: '' },
  { addr: 'A308.0', label: '' },
  { addr: 'A308.1', label: '' },
  { addr: 'A308.2', label: '' },
  { addr: 'A308.3', label: '' },
  { addr: 'A308.4', label: '' },
  { addr: 'A308.5', label: '' },
  { addr: 'A308.6', label: '' },
  { addr: 'A308.7', label: '' },
  { addr: 'A309.0', label: '' },
  { addr: 'A309.1', label: '' },
  { addr: 'A309.2', label: '' },
  { addr: 'A309.3', label: '' },
  { addr: 'A309.4', label: '' },
  { addr: 'A309.5', label: '' },
  { addr: 'A309.6', label: '' },
  { addr: 'A309.7', label: '' }
]
exports.outputs5 = [
  { addr: 'A400.0', label: '' },
  { addr: 'A400.1', label: '' },
  { addr: 'A400.2', label: '' },
  { addr: 'A400.3', label: '' },
  { addr: 'A400.4', label: '' },
  { addr: 'A400.5', label: '' },
  { addr: 'A400.6', label: '' },
  { addr: 'A400.7', label: '' },
  { addr: 'A401.0', label: 'T101' },
  { addr: 'A401.1', label: 'T2' },
  { addr: 'A401.2', label: 'T10F' },
  { addr: 'A401.3', label: 'T102' },
  { addr: 'A401.4', label: 'KBA1' },
  { addr: 'A401.5', label: 'KBA2' },
  { addr: 'A401.6', label: '' },
  { addr: 'A401.7', label: '' }
]
exports.outputs6 = [
  { addr: 'A410.0', label: 'DYA' },
  { addr: 'A410.1', label: 'DYB' },
  { addr: 'A410.2', label: 'DYC' },
  { addr: 'A410.3', label: 'DYD' },
  { addr: 'A410.4', label: 'AD1' },
  { addr: 'A410.5', label: 'AD2' },
  { addr: 'A410.6', label: 'AD3' },
  { addr: 'A410.7', label: 'STR' },
  { addr: 'A411.0', label: 'SBK1' },
  { addr: 'A411.1', label: '' },
  { addr: 'A411.2', label: 'TRA' },
  { addr: 'A411.3', label: 'TRB' },
  { addr: 'A411.4', label: 'TCS' },
  { addr: 'A411.5', label: 'TCV' },
  { addr: 'A411.6', label: 'TCH' },
  { addr: 'A411.7', label: 'TCR' },
  { addr: 'A412.0', label: 'SBK2' },
  { addr: 'A412.1', label: '' },
  { addr: 'A412.2', label: '' },
  { addr: 'A412.3', label: '' },
  { addr: 'A412.4', label: '' },
  { addr: 'A412.5', label: '' },
  { addr: 'A412.6', label: 'LA' },
  { addr: 'A412.7', label: 'LC' },
  { addr: 'A413.0', label: '' },
  { addr: 'A413.1', label: '' },
  { addr: 'A413.2', label: '' },
  { addr: 'A413.3', label: '' },
  { addr: 'A413.4', label: '' },
  { addr: 'A413.5', label: '' },
  { addr: 'A413.6', label: '' },
  { addr: 'A413.7', label: '' }
]
exports.outputs7 = [
  { addr: 'A500.0', label: '' },
  { addr: 'A500.1', label: '' },
  { addr: 'A500.2', label: '' },
  { addr: 'A500.3', label: '' },
  { addr: 'A500.4', label: '' },
  { addr: 'A500.5', label: '' },
  { addr: 'A500.6', label: '' },
  { addr: 'A500.7', label: '' },
  { addr: 'A501.0', label: 'T101' },
  { addr: 'A501.1', label: 'T2' },
  { addr: 'A501.2', label: 'T10F' },
  { addr: 'A501.3', label: 'T102' },
  { addr: 'A501.4', label: 'KBA1' },
  { addr: 'A501.5', label: 'KBA2' },
  { addr: 'A501.6', label: '' },
  { addr: 'A501.7', label: '' }
]
exports.outputs8 = [
  { addr: 'A510.0', label: 'DYA' },
  { addr: 'A510.1', label: 'DYB' },
  { addr: 'A510.2', label: 'DYC' },
  { addr: 'A510.3', label: 'DYD' },
  { addr: 'A510.4', label: 'AD1' },
  { addr: 'A510.5', label: 'AD2' },
  { addr: 'A510.6', label: 'AD3' },
  { addr: 'A510.7', label: 'STR' },
  { addr: 'A511.0', label: 'SBK1' },
  { addr: 'A511.1', label: '' },
  { addr: 'A511.2', label: 'TRA' },
  { addr: 'A511.3', label: 'TRB' },
  { addr: 'A511.4', label: 'TCS' },
  { addr: 'A511.5', label: 'TCV' },
  { addr: 'A511.6', label: 'TCH' },
  { addr: 'A511.7', label: 'TCR' },
  { addr: 'A512.0', label: 'SBK2' },
  { addr: 'A512.1', label: '' },
  { addr: 'A512.2', label: '' },
  { addr: 'A512.3', label: '' },
  { addr: 'A512.4', label: '' },
  { addr: 'A512.5', label: '' },
  { addr: 'A512.6', label: 'LA' },
  { addr: 'A512.7', label: 'LC' },
  { addr: 'A513.0', label: '' },
  { addr: 'A513.1', label: '' },
  { addr: 'A513.2', label: '' },
  { addr: 'A513.3', label: '' },
  { addr: 'A513.4', label: '' },
  { addr: 'A513.5', label: '' },
  { addr: 'A513.6', label: '' },
  { addr: 'A513.7', label: '' }
]
exports.outputs9 = [
  { addr: 'A600.0', label: '' },
  { addr: 'A600.1', label: '' },
  { addr: 'A600.2', label: '' },
  { addr: 'A600.3', label: '' },
  { addr: 'A600.4', label: '' },
  { addr: 'A600.5', label: '' },
  { addr: 'A600.6', label: '' },
  { addr: 'A600.7', label: '' },
  { addr: 'A601.0', label: 'T101' },
  { addr: 'A601.1', label: 'T2' },
  { addr: 'A601.2', label: 'T10F' },
  { addr: 'A601.3', label: 'T102' },
  { addr: 'A601.4', label: 'KBA1' },
  { addr: 'A601.5', label: 'KBA2' },
  { addr: 'A601.6', label: '' },
  { addr: 'A601.7', label: '' }
]
exports.outputs10 = [
  { addr: 'A610.0', label: 'DYA' },
  { addr: 'A610.1', label: 'DYB' },
  { addr: 'A610.2', label: 'DYC' },
  { addr: 'A610.3', label: 'DYD' },
  { addr: 'A610.4', label: 'AD1' },
  { addr: 'A610.5', label: 'AD2' },
  { addr: 'A610.6', label: 'AD3' },
  { addr: 'A610.7', label: 'STR' },
  { addr: 'A611.0', label: 'SBK1' },
  { addr: 'A611.1', label: '' },
  { addr: 'A611.2', label: 'TRA' },
  { addr: 'A611.3', label: 'TRB' },
  { addr: 'A611.4', label: 'TCS' },
  { addr: 'A611.5', label: 'TCV' },
  { addr: 'A611.6', label: 'TCH' },
  { addr: 'A611.7', label: 'TCR' },
  { addr: 'A612.0', label: 'SBK2' },
  { addr: 'A612.1', label: '' },
  { addr: 'A612.2', label: '' },
  { addr: 'A612.3', label: '' },
  { addr: 'A612.4', label: '' },
  { addr: 'A612.5', label: '' },
  { addr: 'A612.6', label: 'LA' },
  { addr: 'A612.7', label: 'LC' },
  { addr: 'A613.0', label: '' },
  { addr: 'A613.1', label: '' },
  { addr: 'A613.2', label: '' },
  { addr: 'A613.3', label: '' },
  { addr: 'A613.4', label: '' },
  { addr: 'A613.5', label: '' },
  { addr: 'A613.6', label: '' },
  { addr: 'A613.7', label: '' }
]
exports.merkers = [
  { addr: 'M0.0', label: '' },
  { addr: 'M0.1', label: '' },
  { addr: 'M0.2', label: '' },
  { addr: 'M0.3', label: '' },
  { addr: 'M0.4', label: '' },
  { addr: 'M0.5', label: '' },
  { addr: 'M0.6', label: '' },
  { addr: 'M0.7', label: '' },
  { addr: 'M1.0', label: '' },
  { addr: 'M1.1', label: '' },
  { addr: 'M1.2', label: '' },
  { addr: 'M1.3', label: '' },
  { addr: 'M1.4', label: '' },
  { addr: 'M1.5', label: '' },
  { addr: 'M1.6', label: '' },
  { addr: 'M1.7', label: '' },
  { addr: 'M2.0', label: '' },
  { addr: 'M2.1', label: '' },
  { addr: 'M2.2', label: '' },
  { addr: 'M2.3', label: '' },
  { addr: 'M2.4', label: '' },
  { addr: 'M2.5', label: '' },
  { addr: 'M2.6', label: '' },
  { addr: 'M2.7', label: '' },
  { addr: 'M3.0', label: '' },
  { addr: 'M3.1', label: '' },
  { addr: 'M3.2', label: '' },
  { addr: 'M3.3', label: '' },
  { addr: 'M3.4', label: '' },
  { addr: 'M3.5', label: '' },
  { addr: 'M3.6', label: '' },
  { addr: 'M3.7', label: '' },
  { addr: 'M4.0', label: '' },
  { addr: 'M4.1', label: '' },
  { addr: 'M4.2', label: '' },
  { addr: 'M4.3', label: '' },
  { addr: 'M4.4', label: '' },
  { addr: 'M4.5', label: '' },
  { addr: 'M4.6', label: '' },
  { addr: 'M4.7', label: '' },
  { addr: 'M5.0', label: '' },
  { addr: 'M5.1', label: '' },
  { addr: 'M5.2', label: '' },
  { addr: 'M5.3', label: '' },
  { addr: 'M5.4', label: '' },
  { addr: 'M5.5', label: '' },
  { addr: 'M5.6', label: '' },
  { addr: 'M5.7', label: '' },
  { addr: 'M6.0', label: '' },
  { addr: 'M6.1', label: '' },
  { addr: 'M6.2', label: '' },
  { addr: 'M6.3', label: '' },
  { addr: 'M6.4', label: '' },
  { addr: 'M6.5', label: '' },
  { addr: 'M6.6', label: '' },
  { addr: 'M6.7', label: '' },
  { addr: 'M7.0', label: '' },
  { addr: 'M7.1', label: '' },
  { addr: 'M7.2', label: '' },
  { addr: 'M7.3', label: '' },
  { addr: 'M7.4', label: '' },
  { addr: 'M7.5', label: '' },
  { addr: 'M7.6', label: '' },
  { addr: 'M7.7', label: '' }
]
exports.nodes = [
  { addr: 'PN0.0', label: 'ALL' },
  { addr: 'PN0.1', label: 'LS-A' },
  { addr: 'PN0.2', label: 'IV-A' },
  { addr: 'PN0.3', label: 'LV-A' },
  { addr: 'PN0.4', label: 'ENR-A' },
  { addr: 'PN0.5', label: 'LS-B' },
  { addr: 'PN0.6', label: 'IV-B' },
  { addr: 'PN0.7', label: 'LV-B' },
  { addr: 'PN1.0', label: 'ENR-B' },
  { addr: 'PN1.1', label: 'LS-C' },
  { addr: 'PN1.2', label: 'IV-C' },
  { addr: 'PN1.3', label: 'LV-C' },
  { addr: 'PN1.4', label: 'ENR-C' },
  { addr: 'PN1.5', label: 'LS-T1' },
  { addr: 'PN1.6', label: 'KKP-T1' },
  { addr: 'PN1.7', label: 'IV1-T1' },
  { addr: 'PN2.0', label: 'IV2-T1' },
  { addr: 'PN2.1', label: 'LV1-T1' },
  { addr: 'PN2.2', label: 'LV2-T1' },
  { addr: 'PN2.3', label: 'LH1-T1' },
  { addr: 'PN2.4', label: 'LH2-T1' },
  { addr: 'PN2.5', label: 'LS-T2' },
  { addr: 'PN2.6', label: 'KKP-T2' },
  { addr: 'PN2.7', label: 'IV1-T2' },
  { addr: 'PN3.0', label: 'IV2-T2' },
  { addr: 'PN3.1', label: 'LV1-T2' },
  { addr: 'PN3.2', label: 'LV2-T2' },
  { addr: 'PN3.3', label: 'LH1-T2' },
  { addr: 'PN3.4', label: 'LS-T3' },
  { addr: 'PN3.5', label: 'KKP-T3' },
  { addr: 'PN3.6', label: 'IV1-T3' },
  { addr: 'PN3.7', label: 'IV2-T3' },
  { addr: 'PN4.0', label: 'LV1-T3' },
  { addr: 'PN4.1', label: 'LV2-T3' },
  { addr: 'PN4.2', label: 'LH1-T3' },
  { addr: 'PN4.3', label: 'LH2-T3' },
  { addr: 'PN4.4', label: 'LH2-T2' },
  { addr: 'PN4.5', label: '' },
  { addr: 'PN4.6', label: '' },
  { addr: 'PN4.7', label: '' },
  { addr: 'PN5.0', label: '' },
  { addr: 'PN5.1', label: '' },
  { addr: 'PN5.2', label: '' },
  { addr: 'PN5.3', label: '' },
  { addr: 'PN5.4', label: '' },
  { addr: 'PN5.5', label: '' },
  { addr: 'PN5.6', label: '' },
  { addr: 'PN5.7', label: '' },
  { addr: 'PN6.0', label: '' },
  { addr: 'PN6.1', label: '' },
  { addr: 'PN6.2', label: '' },
  { addr: 'PN6.3', label: '' },
  { addr: 'PN6.4', label: '' },
  { addr: 'PN6.5', label: '' },
  { addr: 'PN6.6', label: '' },
  { addr: 'PN6.7', label: '' },
  { addr: 'PN7.0', label: '' },
  { addr: 'PN7.1', label: '' },
  { addr: 'PN7.2', label: '' },
  { addr: 'PN7.3', label: '' },
  { addr: 'PN7.4', label: '' },
  { addr: 'PN7.5', label: '' },
  { addr: 'PN7.6', label: '' },
  { addr: 'PN7.7', label: '' }
]
exports.motors = [
  { addr: 'MT0.0', label: 'M1-ENB-T1' },
  { addr: 'MT0.1', label: 'M1-BWD-T1' },
  { addr: 'MT0.2', label: 'M1-FWD-T1' },
  { addr: 'MT0.3', label: 'M2-ENB-T1' },
  { addr: 'MT0.4', label: 'M2-BWD-T1' },
  { addr: 'MT0.5', label: 'M2-FWD-T1' },
  { addr: 'MT0.6', label: 'SIL-ENB-T1' },
  { addr: 'MT0.7', label: 'SIL-BWD-T1' },
  { addr: 'MT1.0', label: 'SIL-FWD-T1' },
  { addr: 'MT1.1', label: 'SIL-UP-T1' },
  { addr: 'MT1.2', label: 'SIL-DOWN-T1' },
  { addr: 'MT1.3', label: 'SIL-OPV-T1' },
  { addr: 'MT1.4', label: 'SIL-CLV-T1' },
  { addr: 'MT1.5', label: 'SIL-OPH-T1' },
  { addr: 'MT1.6', label: 'SIL-CLH-T1' },
  { addr: 'MT1.7', label: '' },
  { addr: 'MT2.0', label: 'M1-ENB-T2' },
  { addr: 'MT2.1', label: 'M1-BWD-T2' },
  { addr: 'MT2.2', label: 'M1-FWD-T2' },
  { addr: 'MT2.3', label: 'M2-ENB-T2' },
  { addr: 'MT2.4', label: 'M2-BWD-T2' },
  { addr: 'MT2.5', label: 'M2-FWD-T2' },
  { addr: 'MT2.6', label: 'SIL-ENB-T2' },
  { addr: 'MT2.7', label: 'SIL-BWD-T2' },
  { addr: 'MT3.0', label: 'SIL-FWD-T2' },
  { addr: 'MT3.1', label: 'SIL-UP-T2' },
  { addr: 'MT3.2', label: 'SIL-DOWN-T2' },
  { addr: 'MT3.3', label: 'SIL-OPV-T2' },
  { addr: 'MT3.4', label: 'SIL-CLV-T2' },
  { addr: 'MT3.5', label: 'SIL-OPH-T2' },
  { addr: 'MT3.6', label: 'SIL-CLH-T2' },
  { addr: 'MT3.7', label: '' },
  { addr: 'MT4.0', label: 'M1-ENB-T3' },
  { addr: 'MT4.1', label: 'M1-BWD-T3' },
  { addr: 'MT4.2', label: 'M1-FWD-T3' },
  { addr: 'MT4.3', label: 'M2-ENB-T3' },
  { addr: 'MT4.4', label: 'M2-BWD-T3' },
  { addr: 'MT4.5', label: 'M2-FWD-T3' },
  { addr: 'MT4.6', label: 'SIL-ENB-T3' },
  { addr: 'MT4.7', label: 'SIL-BWD-T3' },
  { addr: 'MT5.0', label: 'SIL-FWD-T3' },
  { addr: 'MT5.1', label: 'SIL-UP-T3' },
  { addr: 'MT5.2', label: 'SIL-DOWN-T3' },
  { addr: 'MT5.3', label: 'SIL-OPV-T3' },
  { addr: 'MT5.4', label: 'SIL-CLV-T3' },
  { addr: 'MT5.5', label: 'SIL-OPH-T3' },
  { addr: 'MT5.6', label: 'SIL-CLH-T3' },
  { addr: 'MT5.7', label: '' },
  { addr: 'MT6.0', label: 'M1-ENB-A' },
  { addr: 'MT6.1', label: 'M1-BWD-A' },
  { addr: 'MT6.2', label: 'M1-FWD-A' },
  { addr: 'MT6.3', label: 'M2-ENB-A' },
  { addr: 'MT6.4', label: 'M2-BWD-A' },
  { addr: 'MT6.5', label: 'M2-FWD-A' },
  { addr: 'MT6.6', label: 'M3-ENB-A' },
  { addr: 'MT6.7', label: 'M3-BWD-A' },
  { addr: 'MT7.0', label: 'M3-FWD-A' },
  { addr: 'MT7.1', label: 'M4-ENB-A' },
  { addr: 'MT7.2', label: 'M4-BWD-A' },
  { addr: 'MT7.3', label: 'M4-FWD-A' },
  { addr: 'MT7.4', label: 'M5-ENB-A' },
  { addr: 'MT7.5', label: 'M5-BWD-A' },
  { addr: 'MT7.6', label: 'M5-FWD-A' },
  { addr: 'MT7.7', label: 'M6-ENB-A' },
  { addr: 'MT8.0', label: 'M6-BWD-A' },
  { addr: 'MT8.1', label: 'M6-FWD-A' },
  { addr: 'MT8.2', label: '' },
  { addr: 'MT8.3', label: '' },
  { addr: 'MT8.4', label: '' },
  { addr: 'MT8.5', label: '' },
  { addr: 'MT8.6', label: '' },
  { addr: 'MT8.7', label: '' },
  { addr: 'MT9.0', label: 'M1-ENB-B' },
  { addr: 'MT9.1', label: 'M1-BWD-B' },
  { addr: 'MT9.2', label: 'M1-FWD-B' },
  { addr: 'MT9.3', label: 'M2-ENB-B' },
  { addr: 'MT9.4', label: 'M2-BWD-B' },
  { addr: 'MT9.5', label: 'M2-FWD-B' },
  { addr: 'MT9.6', label: 'M3-ENB-B' },
  { addr: 'MT9.7', label: 'M3-BWD-B' },
  { addr: 'MT10.0', label: 'M3-FWD-B' },
  { addr: 'MT10.1', label: 'M4-ENB-B' },
  { addr: 'MT10.2', label: 'M4-BWD-B' },
  { addr: 'MT10.3', label: 'M4-FWD-B' },
  { addr: 'MT10.4', label: 'M5-ENB-B' },
  { addr: 'MT10.5', label: 'M5-BWD-B' },
  { addr: 'MT10.6', label: 'M5-FWD-B' },
  { addr: 'MT10.7', label: 'M6-ENB-B' },
  { addr: 'MT11.0', label: 'M6-BWD-B' },
  { addr: 'MT11.1', label: 'M6-FWD-B' },
  { addr: 'MT11.2', label: '' },
  { addr: 'MT11.3', label: '' },
  { addr: 'MT11.4', label: '' },
  { addr: 'MT11.5', label: '' },
  { addr: 'MT11.6', label: '' },
  { addr: 'MT11.7', label: '' },
  { addr: 'MT12.0', label: 'M1-ENB-C' },
  { addr: 'MT12.1', label: 'M1-BWD-C' },
  { addr: 'MT12.2', label: 'M1-FWD-C' },
  { addr: 'MT12.3', label: 'M2-ENB-C' },
  { addr: 'MT12.4', label: 'M2-BWD-C' },
  { addr: 'MT12.5', label: 'M2-FWD-C' },
  { addr: 'MT12.6', label: 'M3-ENB-C' },
  { addr: 'MT12.7', label: 'M3-BWD-C' },
  { addr: 'MT13.0', label: 'M3-FWD-C' },
  { addr: 'MT13.1', label: 'M4-ENB-C' },
  { addr: 'MT13.2', label: 'M4-BWD-C' },
  { addr: 'MT13.3', label: 'M4-FWD-C' },
  { addr: 'MT13.4', label: 'M5-ENB-C' },
  { addr: 'MT13.5', label: 'M5-BWD-C' },
  { addr: 'MT13.6', label: 'M5-FWD-C' },
  { addr: 'MT13.7', label: 'M6-ENB-C' },
  { addr: 'MT14.0', label: 'M6-BWD-C' },
  { addr: 'MT14.1', label: 'M6-FWD-C' },
  { addr: 'MT14.2', label: '' },
  { addr: 'MT14.3', label: '' },
  { addr: 'MT14.4', label: '' },
  { addr: 'MT14.5', label: '' },
  { addr: 'MT14.6', label: '' },
  { addr: 'MT14.7', label: '' },
  { addr: 'MT15.0', label: '' },
  { addr: 'MT15.1', label: '' },
  { addr: 'MT15.2', label: '' },
  { addr: 'MT15.3', label: '' },
  { addr: 'MT15.4', label: '' },
  { addr: 'MT15.5', label: '' },
  { addr: 'MT15.6', label: '' },
  { addr: 'MT15.7', label: '' }
]
exports.alarms1 = [
  { class: 'EVT1', label: 'AL1', info: 'al-sil-01' },
  { class: 'EVT1', label: 'AL2', info: 'al-sil-02' },
  { class: 'EVT1', label: 'AL3', info: 'al-sil-03' },
  { class: 'EVT1', label: 'AL4', info: 'al-sil-04' },
  { class: 'EVT1', label: 'AL5', info: 'al-sil-05' },
  { class: 'EVT1', label: 'AL6', info: 'al-sil-06' },
  { class: 'EVT1', label: 'AL7', info: 'al-sil-07' },
  { class: 'EVT1', label: 'AL8', info: 'al-sil-08' },
  { class: 'EVT1', label: 'AL9', info: 'al-sil-09' },
  { class: 'EVT1', label: 'AL10', info: 'al-sil-10' },
  { class: 'EVT1', label: 'AL11', info: 'al-sil-11' },
  { class: 'EVT1', label: 'AL12', info: 'al-sil-12' },
  { class: 'EVT1', label: 'AL13', info: 'al-sil-13' },
  { class: 'EVT1', label: 'AL14', info: 'al-sil-14' },
  { class: 'EVT1', label: 'AL15', info: 'al-sil-15' },
  { class: 'EVT1', label: 'AL16', info: 'al-sil-16' },
  { class: 'EVT1', label: 'AL17', info: 'al-v-to' },
  { class: 'EVT1', label: 'AL18', info: 'al-v-fdbk' },
  { class: 'EVT1', label: 'AL19', info: 'al-lv' },
  { class: 'EVT1', label: 'AL20', info: 'al-v-lck-to' },
  { class: 'EVT1', label: 'AL21', info: 'al-v-lck-fc' },
  { class: 'EVT1', label: 'AL22', info: 'al-r-to' },
  { class: 'EVT1', label: 'AL23', info: 'al-enr' },
  { class: 'EVT1', label: 'AL24', info: 'al-r-lck-to' },
  { class: 'EVT1', label: 'AL25', info: 'al-r-lck-fc' },
  { class: 'EVT1', label: 'AL26', info: 'al-flap-to' },
  { class: 'EVT1', label: 'AL27', info: 'al-flap-fc' },
  { class: 'EVT1', label: 'AL28', info: 'al-sp-to' },
  { class: 'EVT1', label: 'AL29', info: 'al-sp-fc' },
  { class: 'EVT1', label: 'AL30', info: '' },
  { class: 'EVT1', label: 'AL31', info: '' },
  { class: 'EVT1', label: 'AL32', info: '' },
  { class: 'EVT1', label: 'AL33', info: '' },
  { class: 'EVT1', label: 'AL34', info: '' },
  { class: 'EVT1', label: 'AL35', info: '' },
  { class: 'EVT1', label: 'AL36', info: '' },
  { class: 'EVT1', label: 'AL37', info: '' },
  { class: 'EVT1', label: 'AL38', info: '' },
  { class: 'EVT1', label: 'AL39', info: '' },
  { class: 'EVT1', label: 'AL40', info: '' },
  { class: 'EVT1', label: 'AL41', info: '' },
  { class: 'EVT1', label: 'AL42', info: '' },
  { class: 'EVT1', label: 'AL43', info: '' },
  { class: 'EVT1', label: 'AL44', info: '' },
  { class: 'EVT1', label: 'AL45', info: '' },
  { class: 'EVT1', label: 'AL46', info: '' },
  { class: 'EVT1', label: 'AL47', info: '' },
  { class: 'EVT1', label: 'AL48', info: '' },
  { class: 'EVT1', label: 'AL49', info: '' },
  { class: 'EVT1', label: 'AL50', info: '' },
  { class: 'EVT1', label: 'AL51', info: '' },
  { class: 'EVT1', label: 'AL52', info: '' },
  { class: 'EVT1', label: 'AL53', info: '' },
  { class: 'EVT1', label: 'AL54', info: '' },
  { class: 'EVT1', label: 'AL55', info: '' },
  { class: 'EVT1', label: 'AL56', info: '' },
  { class: 'EVT1', label: 'AL57', info: '' },
  { class: 'EVT1', label: 'AL58', info: '' },
  { class: 'EVT1', label: 'AL59', info: '' },
  { class: 'EVT1', label: 'AL60', info: '' },
  { class: 'EVT1', label: 'AL61', info: '' },
  { class: 'EVT1', label: 'AL62', info: '' },
  { class: 'EVT1', label: 'AL63', info: '' },
  { class: 'EVT1', label: 'AL64', info: '' }
]
exports.alarms2 = [
  { class: 'EVT2', label: 'AL1', info: 'al-sil-01' },
  { class: 'EVT2', label: 'AL2', info: 'al-sil-02' },
  { class: 'EVT2', label: 'AL3', info: 'al-sil-03' },
  { class: 'EVT2', label: 'AL4', info: 'al-sil-04' },
  { class: 'EVT2', label: 'AL5', info: 'al-sil-05' },
  { class: 'EVT2', label: 'AL6', info: 'al-sil-06' },
  { class: 'EVT2', label: 'AL7', info: 'al-sil-07' },
  { class: 'EVT2', label: 'AL8', info: 'al-sil-08' },
  { class: 'EVT2', label: 'AL9', info: 'al-sil-09' },
  { class: 'EVT2', label: 'AL10', info: 'al-sil-10' },
  { class: 'EVT2', label: 'AL11', info: 'al-sil-11' },
  { class: 'EVT2', label: 'AL12', info: 'al-sil-12' },
  { class: 'EVT2', label: 'AL13', info: 'al-sil-13' },
  { class: 'EVT2', label: 'AL14', info: 'al-sil-14' },
  { class: 'EVT2', label: 'AL15', info: 'al-sil-15' },
  { class: 'EVT2', label: 'AL16', info: 'al-sil-16' },
  { class: 'EVT2', label: 'AL17', info: 'al-v-to' },
  { class: 'EVT2', label: 'AL18', info: 'al-v-fdbk' },
  { class: 'EVT2', label: 'AL19', info: 'al-lv' },
  { class: 'EVT2', label: 'AL20', info: 'al-v-lck-to' },
  { class: 'EVT2', label: 'AL21', info: 'al-v-lck-fc' },
  { class: 'EVT2', label: 'AL22', info: 'al-r-to' },
  { class: 'EVT2', label: 'AL23', info: 'al-enr' },
  { class: 'EVT2', label: 'AL24', info: 'al-r-lck-to' },
  { class: 'EVT2', label: 'AL25', info: 'al-r-lck-fc' },
  { class: 'EVT2', label: 'AL26', info: 'al-flap-to' },
  { class: 'EVT2', label: 'AL27', info: 'al-flap-fc' },
  { class: 'EVT2', label: 'AL28', info: 'al-sp-to' },
  { class: 'EVT2', label: 'AL29', info: 'al-sp-fc' },
  { class: 'EVT2', label: 'AL30', info: '' },
  { class: 'EVT2', label: 'AL31', info: '' },
  { class: 'EVT2', label: 'AL32', info: '' },
  { class: 'EVT2', label: 'AL33', info: '' },
  { class: 'EVT2', label: 'AL34', info: '' },
  { class: 'EVT2', label: 'AL35', info: '' },
  { class: 'EVT2', label: 'AL36', info: '' },
  { class: 'EVT2', label: 'AL37', info: '' },
  { class: 'EVT2', label: 'AL38', info: '' },
  { class: 'EVT2', label: 'AL39', info: '' },
  { class: 'EVT2', label: 'AL40', info: '' },
  { class: 'EVT2', label: 'AL41', info: '' },
  { class: 'EVT2', label: 'AL42', info: '' },
  { class: 'EVT2', label: 'AL43', info: '' },
  { class: 'EVT2', label: 'AL44', info: '' },
  { class: 'EVT2', label: 'AL45', info: '' },
  { class: 'EVT2', label: 'AL46', info: '' },
  { class: 'EVT2', label: 'AL47', info: '' },
  { class: 'EVT2', label: 'AL48', info: '' },
  { class: 'EVT2', label: 'AL49', info: '' },
  { class: 'EVT2', label: 'AL50', info: '' },
  { class: 'EVT2', label: 'AL51', info: '' },
  { class: 'EVT2', label: 'AL52', info: '' },
  { class: 'EVT2', label: 'AL53', info: '' },
  { class: 'EVT2', label: 'AL54', info: '' },
  { class: 'EVT2', label: 'AL55', info: '' },
  { class: 'EVT2', label: 'AL56', info: '' },
  { class: 'EVT2', label: 'AL57', info: '' },
  { class: 'EVT2', label: 'AL58', info: '' },
  { class: 'EVT2', label: 'AL59', info: '' },
  { class: 'EVT2', label: 'AL60', info: '' },
  { class: 'EVT2', label: 'AL61', info: '' },
  { class: 'EVT2', label: 'AL62', info: '' },
  { class: 'EVT2', label: 'AL63', info: '' },
  { class: 'EVT2', label: 'AL64', info: '' }
]
exports.alarms3 = [
  { class: 'EVT3', label: 'AL1', info: 'al-sil-01' },
  { class: 'EVT3', label: 'AL2', info: 'al-sil-02' },
  { class: 'EVT3', label: 'AL3', info: 'al-sil-03' },
  { class: 'EVT3', label: 'AL4', info: 'al-sil-04' },
  { class: 'EVT3', label: 'AL5', info: 'al-sil-05' },
  { class: 'EVT3', label: 'AL6', info: 'al-sil-06' },
  { class: 'EVT3', label: 'AL7', info: 'al-sil-07' },
  { class: 'EVT3', label: 'AL8', info: 'al-sil-08' },
  { class: 'EVT3', label: 'AL9', info: 'al-sil-09' },
  { class: 'EVT3', label: 'AL10', info: 'al-sil-10' },
  { class: 'EVT3', label: 'AL11', info: 'al-sil-11' },
  { class: 'EVT3', label: 'AL12', info: 'al-sil-12' },
  { class: 'EVT3', label: 'AL13', info: 'al-sil-13' },
  { class: 'EVT3', label: 'AL14', info: 'al-sil-14' },
  { class: 'EVT3', label: 'AL15', info: 'al-sil-15' },
  { class: 'EVT3', label: 'AL16', info: 'al-sil-16' },
  { class: 'EVT3', label: 'AL17', info: 'al-v-to' },
  { class: 'EVT3', label: 'AL18', info: 'al-v-fdbk' },
  { class: 'EVT3', label: 'AL19', info: 'al-lv' },
  { class: 'EVT3', label: 'AL20', info: 'al-v-lck-to' },
  { class: 'EVT3', label: 'AL21', info: 'al-v-lck-fc' },
  { class: 'EVT3', label: 'AL22', info: 'al-r-to' },
  { class: 'EVT3', label: 'AL23', info: 'al-enr' },
  { class: 'EVT3', label: 'AL24', info: 'al-r-lck-to' },
  { class: 'EVT3', label: 'AL25', info: 'al-r-lck-fc' },
  { class: 'EVT3', label: 'AL26', info: 'al-flap-to' },
  { class: 'EVT3', label: 'AL27', info: 'al-flap-fc' },
  { class: 'EVT3', label: 'AL28', info: 'al-sp-to' },
  { class: 'EVT3', label: 'AL29', info: 'al-sp-fc' },
  { class: 'EVT3', label: 'AL30', info: '' },
  { class: 'EVT3', label: 'AL31', info: '' },
  { class: 'EVT3', label: 'AL32', info: '' },
  { class: 'EVT3', label: 'AL33', info: '' },
  { class: 'EVT3', label: 'AL34', info: '' },
  { class: 'EVT3', label: 'AL35', info: '' },
  { class: 'EVT3', label: 'AL36', info: '' },
  { class: 'EVT3', label: 'AL37', info: '' },
  { class: 'EVT3', label: 'AL38', info: '' },
  { class: 'EVT3', label: 'AL39', info: '' },
  { class: 'EVT3', label: 'AL40', info: '' },
  { class: 'EVT3', label: 'AL41', info: '' },
  { class: 'EVT3', label: 'AL42', info: '' },
  { class: 'EVT3', label: 'AL43', info: '' },
  { class: 'EVT3', label: 'AL44', info: '' },
  { class: 'EVT3', label: 'AL45', info: '' },
  { class: 'EVT3', label: 'AL46', info: '' },
  { class: 'EVT3', label: 'AL47', info: '' },
  { class: 'EVT3', label: 'AL48', info: '' },
  { class: 'EVT3', label: 'AL49', info: '' },
  { class: 'EVT3', label: 'AL50', info: '' },
  { class: 'EVT3', label: 'AL51', info: '' },
  { class: 'EVT3', label: 'AL52', info: '' },
  { class: 'EVT3', label: 'AL53', info: '' },
  { class: 'EVT3', label: 'AL54', info: '' },
  { class: 'EVT3', label: 'AL55', info: '' },
  { class: 'EVT3', label: 'AL56', info: '' },
  { class: 'EVT3', label: 'AL57', info: '' },
  { class: 'EVT3', label: 'AL58', info: '' },
  { class: 'EVT3', label: 'AL59', info: '' },
  { class: 'EVT3', label: 'AL60', info: '' },
  { class: 'EVT3', label: 'AL61', info: '' },
  { class: 'EVT3', label: 'AL62', info: '' },
  { class: 'EVT3', label: 'AL63', info: '' },
  { class: 'EVT3', label: 'AL64', info: '' }
]
exports.alarms4 = [
  { class: 'IVT1', label: 'AL1', info: 'al-sil-01' },
  { class: 'IVT1', label: 'AL2', info: 'al-sil-02' },
  { class: 'IVT1', label: 'AL3', info: 'al-sil-03' },
  { class: 'IVT1', label: 'AL4', info: 'al-sil-04' },
  { class: 'IVT1', label: 'AL5', info: 'al-sil-05' },
  { class: 'IVT1', label: 'AL6', info: 'al-sil-06' },
  { class: 'IVT1', label: 'AL7', info: 'al-sil-07' },
  { class: 'IVT1', label: 'AL8', info: 'al-sil-08' },
  { class: 'IVT1', label: 'AL9', info: 'al-sil-09' },
  { class: 'IVT1', label: 'AL10', info: 'al-sil-10' },
  { class: 'IVT1', label: 'AL11', info: 'al-sil-11' },
  { class: 'IVT1', label: 'AL12', info: 'al-sil-12' },
  { class: 'IVT1', label: 'AL13', info: 'al-sil-13' },
  { class: 'IVT1', label: 'AL14', info: 'al-sil-14' },
  { class: 'IVT1', label: 'AL15', info: 'al-sil-15' },
  { class: 'IVT1', label: 'AL16', info: 'al-sil-16' },
  { class: 'IVT1', label: 'AL17', info: 'al-v-to' },
  { class: 'IVT1', label: 'AL18', info: 'al-v-fdbk' },
  { class: 'IVT1', label: 'AL19', info: 'al-lv' },
  { class: 'IVT1', label: 'AL20', info: 'al-lv-diff' },
  { class: 'IVT1', label: 'AL21', info: 'al-h-to' },
  { class: 'IVT1', label: 'AL22', info: 'al-lh' },
  { class: 'IVT1', label: 'AL23', info: 'al-lh-diff' },
  { class: 'IVT1', label: 'AL24', info: '' },
  { class: 'IVT1', label: 'AL25', info: '' },
  { class: 'IVT1', label: 'AL26', info: '' },
  { class: 'IVT1', label: 'AL27', info: '' },
  { class: 'IVT1', label: 'AL28', info: '' },
  { class: 'IVT1', label: 'AL29', info: '' },
  { class: 'IVT1', label: 'AL30', info: '' },
  { class: 'IVT1', label: 'AL31', info: '' },
  { class: 'IVT1', label: 'AL32', info: '' },
  { class: 'IVT1', label: 'AL33', info: '' },
  { class: 'IVT1', label: 'AL34', info: '' },
  { class: 'IVT1', label: 'AL35', info: '' },
  { class: 'IVT1', label: 'AL36', info: '' },
  { class: 'IVT1', label: 'AL37', info: '' },
  { class: 'IVT1', label: 'AL38', info: '' },
  { class: 'IVT1', label: 'AL39', info: '' },
  { class: 'IVT1', label: 'AL40', info: '' },
  { class: 'IVT1', label: 'AL41', info: '' },
  { class: 'IVT1', label: 'AL42', info: '' },
  { class: 'IVT1', label: 'AL43', info: '' },
  { class: 'IVT1', label: 'AL44', info: '' },
  { class: 'IVT1', label: 'AL45', info: '' },
  { class: 'IVT1', label: 'AL46', info: '' },
  { class: 'IVT1', label: 'AL47', info: '' },
  { class: 'IVT1', label: 'AL48', info: '' },
  { class: 'IVT1', label: 'AL49', info: '' },
  { class: 'IVT1', label: 'AL50', info: '' },
  { class: 'IVT1', label: 'AL51', info: '' },
  { class: 'IVT1', label: 'AL52', info: '' },
  { class: 'IVT1', label: 'AL53', info: '' },
  { class: 'IVT1', label: 'AL54', info: '' },
  { class: 'IVT1', label: 'AL55', info: '' },
  { class: 'IVT1', label: 'AL56', info: '' },
  { class: 'IVT1', label: 'AL57', info: '' },
  { class: 'IVT1', label: 'AL58', info: '' },
  { class: 'IVT1', label: 'AL59', info: '' },
  { class: 'IVT1', label: 'AL60', info: '' },
  { class: 'IVT1', label: 'AL61', info: '' },
  { class: 'IVT1', label: 'AL62', info: '' },
  { class: 'IVT1', label: 'AL63', info: '' },
  { class: 'IVT1', label: 'AL64', info: '' }
]
exports.alarms5 = [
  { class: 'IVT2', label: 'AL1', info: 'al-sil-01' },
  { class: 'IVT2', label: 'AL2', info: 'al-sil-02' },
  { class: 'IVT2', label: 'AL3', info: 'al-sil-03' },
  { class: 'IVT2', label: 'AL4', info: 'al-sil-04' },
  { class: 'IVT2', label: 'AL5', info: 'al-sil-05' },
  { class: 'IVT2', label: 'AL6', info: 'al-sil-06' },
  { class: 'IVT2', label: 'AL7', info: 'al-sil-07' },
  { class: 'IVT2', label: 'AL8', info: 'al-sil-08' },
  { class: 'IVT2', label: 'AL9', info: 'al-sil-09' },
  { class: 'IVT2', label: 'AL10', info: 'al-sil-10' },
  { class: 'IVT2', label: 'AL11', info: 'al-sil-11' },
  { class: 'IVT2', label: 'AL12', info: 'al-sil-12' },
  { class: 'IVT2', label: 'AL13', info: 'al-sil-13' },
  { class: 'IVT2', label: 'AL14', info: 'al-sil-14' },
  { class: 'IVT2', label: 'AL15', info: 'al-sil-15' },
  { class: 'IVT2', label: 'AL16', info: 'al-sil-16' },
  { class: 'IVT2', label: 'AL17', info: 'al-v-to' },
  { class: 'IVT2', label: 'AL18', info: 'al-v-fdbk' },
  { class: 'IVT2', label: 'AL19', info: 'al-lv' },
  { class: 'IVT2', label: 'AL20', info: 'al-lv-diff' },
  { class: 'IVT2', label: 'AL21', info: 'al-h-to' },
  { class: 'IVT2', label: 'AL22', info: 'al-lh' },
  { class: 'IVT2', label: 'AL23', info: 'al-lh-diff' },
  { class: 'IVT2', label: 'AL24', info: '' },
  { class: 'IVT2', label: 'AL25', info: '' },
  { class: 'IVT2', label: 'AL26', info: '' },
  { class: 'IVT2', label: 'AL27', info: '' },
  { class: 'IVT2', label: 'AL28', info: '' },
  { class: 'IVT2', label: 'AL29', info: '' },
  { class: 'IVT2', label: 'AL30', info: '' },
  { class: 'IVT2', label: 'AL31', info: '' },
  { class: 'IVT2', label: 'AL32', info: '' },
  { class: 'IVT2', label: 'AL33', info: '' },
  { class: 'IVT2', label: 'AL34', info: '' },
  { class: 'IVT2', label: 'AL35', info: '' },
  { class: 'IVT2', label: 'AL36', info: '' },
  { class: 'IVT2', label: 'AL37', info: '' },
  { class: 'IVT2', label: 'AL38', info: '' },
  { class: 'IVT2', label: 'AL39', info: '' },
  { class: 'IVT2', label: 'AL40', info: '' },
  { class: 'IVT2', label: 'AL41', info: '' },
  { class: 'IVT2', label: 'AL42', info: '' },
  { class: 'IVT2', label: 'AL43', info: '' },
  { class: 'IVT2', label: 'AL44', info: '' },
  { class: 'IVT2', label: 'AL45', info: '' },
  { class: 'IVT2', label: 'AL46', info: '' },
  { class: 'IVT2', label: 'AL47', info: '' },
  { class: 'IVT2', label: 'AL48', info: '' },
  { class: 'IVT2', label: 'AL49', info: '' },
  { class: 'IVT2', label: 'AL50', info: '' },
  { class: 'IVT2', label: 'AL51', info: '' },
  { class: 'IVT2', label: 'AL52', info: '' },
  { class: 'IVT2', label: 'AL53', info: '' },
  { class: 'IVT2', label: 'AL54', info: '' },
  { class: 'IVT2', label: 'AL55', info: '' },
  { class: 'IVT2', label: 'AL56', info: '' },
  { class: 'IVT2', label: 'AL57', info: '' },
  { class: 'IVT2', label: 'AL58', info: '' },
  { class: 'IVT2', label: 'AL59', info: '' },
  { class: 'IVT2', label: 'AL60', info: '' },
  { class: 'IVT2', label: 'AL61', info: '' },
  { class: 'IVT2', label: 'AL62', info: '' },
  { class: 'IVT2', label: 'AL63', info: '' },
  { class: 'IVT2', label: 'AL64', info: '' }
]
exports.alarms6 = [
  { class: 'IVT3', label: 'AL1', info: 'al-sil-01' },
  { class: 'IVT3', label: 'AL2', info: 'al-sil-02' },
  { class: 'IVT3', label: 'AL3', info: 'al-sil-03' },
  { class: 'IVT3', label: 'AL4', info: 'al-sil-04' },
  { class: 'IVT3', label: 'AL5', info: 'al-sil-05' },
  { class: 'IVT3', label: 'AL6', info: 'al-sil-06' },
  { class: 'IVT3', label: 'AL7', info: 'al-sil-07' },
  { class: 'IVT3', label: 'AL8', info: 'al-sil-08' },
  { class: 'IVT3', label: 'AL9', info: 'al-sil-09' },
  { class: 'IVT3', label: 'AL10', info: 'al-sil-10' },
  { class: 'IVT3', label: 'AL11', info: 'al-sil-11' },
  { class: 'IVT3', label: 'AL12', info: 'al-sil-12' },
  { class: 'IVT3', label: 'AL13', info: 'al-sil-13' },
  { class: 'IVT3', label: 'AL14', info: 'al-sil-14' },
  { class: 'IVT3', label: 'AL15', info: 'al-sil-15' },
  { class: 'IVT3', label: 'AL16', info: 'al-sil-16' },
  { class: 'IVT3', label: 'AL17', info: 'al-v-to' },
  { class: 'IVT3', label: 'AL18', info: 'al-v-fdbk' },
  { class: 'IVT3', label: 'AL19', info: 'al-lv' },
  { class: 'IVT3', label: 'AL20', info: 'al-lv-diff' },
  { class: 'IVT3', label: 'AL21', info: 'al-h-to' },
  { class: 'IVT3', label: 'AL22', info: 'al-lh' },
  { class: 'IVT3', label: 'AL23', info: 'al-lh-diff' },
  { class: 'IVT3', label: 'AL24', info: '' },
  { class: 'IVT3', label: 'AL25', info: '' },
  { class: 'IVT3', label: 'AL26', info: '' },
  { class: 'IVT3', label: 'AL27', info: '' },
  { class: 'IVT3', label: 'AL28', info: '' },
  { class: 'IVT3', label: 'AL29', info: '' },
  { class: 'IVT3', label: 'AL30', info: '' },
  { class: 'IVT3', label: 'AL31', info: '' },
  { class: 'IVT3', label: 'AL32', info: '' },
  { class: 'IVT3', label: 'AL33', info: '' },
  { class: 'IVT3', label: 'AL34', info: '' },
  { class: 'IVT3', label: 'AL35', info: '' },
  { class: 'IVT3', label: 'AL36', info: '' },
  { class: 'IVT3', label: 'AL37', info: '' },
  { class: 'IVT3', label: 'AL38', info: '' },
  { class: 'IVT3', label: 'AL39', info: '' },
  { class: 'IVT3', label: 'AL40', info: '' },
  { class: 'IVT3', label: 'AL41', info: '' },
  { class: 'IVT3', label: 'AL42', info: '' },
  { class: 'IVT3', label: 'AL43', info: '' },
  { class: 'IVT3', label: 'AL44', info: '' },
  { class: 'IVT3', label: 'AL45', info: '' },
  { class: 'IVT3', label: 'AL46', info: '' },
  { class: 'IVT3', label: 'AL47', info: '' },
  { class: 'IVT3', label: 'AL48', info: '' },
  { class: 'IVT3', label: 'AL49', info: '' },
  { class: 'IVT3', label: 'AL50', info: '' },
  { class: 'IVT3', label: 'AL51', info: '' },
  { class: 'IVT3', label: 'AL52', info: '' },
  { class: 'IVT3', label: 'AL53', info: '' },
  { class: 'IVT3', label: 'AL54', info: '' },
  { class: 'IVT3', label: 'AL55', info: '' },
  { class: 'IVT3', label: 'AL56', info: '' },
  { class: 'IVT3', label: 'AL57', info: '' },
  { class: 'IVT3', label: 'AL58', info: '' },
  { class: 'IVT3', label: 'AL59', info: '' },
  { class: 'IVT3', label: 'AL60', info: '' },
  { class: 'IVT3', label: 'AL61', info: '' },
  { class: 'IVT3', label: 'AL62', info: '' },
  { class: 'IVT3', label: 'AL63', info: '' },
  { class: 'IVT3', label: 'AL64', info: '' }
]
